import yfinance as yf
import pandas as pd
import requests
from datetime import datetime, timedelta
import os


ticker_asia = {
    # --- JAPAN (Tokyo Stock Exchange: .T) ---
    '7203.T': 'Toyota Motor Corporation',
    '8306.T': 'Mitsubishi UFJ Financial Group, Inc.',
    '6758.T': 'Sony Group Corporation',
    '6861.T': 'Keyence Corporation',
    '9983.T': 'Fast Retailing Co., Ltd.',
    '9984.T': 'SoftBank Group Corp.',
    '8035.T': 'Tokyo Electron Limited',
    '7974.T': 'Nintendo Co., Ltd.',
    '4502.T': 'Takeda Pharmaceutical Company Limited',
    '6501.T': 'Hitachi, Ltd.',
    '8001.T': 'Itochu Corporation',
    '8031.T': 'Mitsui & Co., Ltd.',
    '8058.T': 'Mitsubishi Corporation',
    '8411.T': 'Mizuho Financial Group, Inc.',
    '9432.T': 'Nippon Telegraph and Telephone Corporation',
    '9433.T': 'KDDI Corporation',
    '9434.T': 'SoftBank Corp.',
    '6098.T': 'Recruit Holdings Co., Ltd.',
    '4063.T': 'Shin-Etsu Chemical Co., Ltd.',
    '4519.T': 'Chugai Pharmaceutical Co., Ltd.',
    '6902.T': 'Denso Corporation',
    '6920.T': 'Lasertec Corporation',
    '7741.T': 'Hoya Corporation',
    '8316.T': 'Sumitomo Mitsui Financial Group, Inc.',
    '8766.T': 'Tokio Marine Holdings, Inc.',
    '2914.T': 'Japan Tobacco Inc.',
    '3382.T': 'Seven & i Holdings Co., Ltd.',
    '4503.T': 'Astellas Pharma Inc.',
    '4901.T': 'Fujifilm Holdings Corporation',
    '6367.T': 'Daikin Industries, Ltd.',
    '6503.T': 'Mitsubishi Electric Corporation',
    '6702.T': 'Fujitsu Limited',
    '6954.T': 'Fanuc Corporation',
    '6971.T': 'Kyocera Corporation',
    '6981.T': 'Murata Manufacturing Co., Ltd.',
    '7267.T': 'Honda Motor Co., Ltd.',
    '7309.T': 'Shimano Inc.',
    '8053.T': 'Sumitomo Corporation',
    '8113.T': 'Unicharm Corporation',
    '8267.T': 'Aeon Co., Ltd.',
    '8604.T': 'Nomura Holdings, Inc.',
    '8801.T': 'Mitsui Fudosan Co., Ltd.',
    '8802.T': 'Mitsubishi Estate Company, Limited',
    '9020.T': 'East Japan Railway Company',
    '9022.T': 'Central Japan Railway Company',
    '9101.T': 'Nippon Yusen Kabushiki Kaisha',
    '9202.T': 'ANA Holdings Inc.',
    '9613.T': 'NTT Data Group Corporation',
    '9735.T': 'Secom Co., Ltd.',
    '9843.T': 'Nitori Holdings Co., Ltd.',
    '1925.T': 'Daiwa House Industry Co., Ltd.',
    '1928.T': 'Sekisui House, Ltd.',
    '2502.T': 'Asahi Group Holdings, Ltd.',
    '2503.T': 'Kirin Holdings Company, Limited',
    '2802.T': 'Ajinomoto Co., Inc.',
    '3407.T': 'Asahi Kasei Corporation',
    '4188.T': 'Mitsubishi Chemical Group Corporation',
    '4452.T': 'Kao Corporation',
    '4523.T': 'Eisai Co., Ltd.',
    '4528.T': 'Ono Pharmaceutical Co., Ltd.',
    '4568.T': 'Daiichi Sankyo Company, Limited',
    '4578.T': 'Ootsuka Holdings Co., Ltd.',
    '4661.T': 'Oriental Land Co., Ltd.',
    '4911.T': 'Shiseido Company, Limited',
    '5020.T': 'ENEOS Holdings, Inc.',
    '5108.T': 'Bridgestone Corporation',
    '5401.T': 'Nippon Steel Corporation',
    '5713.T': 'Sumitomo Metal Mining Co., Ltd.',
    '6178.T': 'Japan Post Holdings Co., Ltd.',
    '6273.T': 'SMC Corporation',
    '6301.T': 'Komatsu Ltd.',
    '6326.T': 'Kubota Corporation',
    '6504.T': 'Fuji Electric Co., Ltd.',
    '6506.T': 'Yaskawa Electric Corporation',
    '6645.T': 'Omron Corporation',
    '6723.T': 'Renesas Electronics Corporation',
    '6752.T': 'Panasonic Holdings Corporation',
    '6762.T': 'TDK Corporation',
    '6857.T': 'Advantest Corporation',
    '7011.T': 'Mitsubishi Heavy Industries, Ltd.',
    '7201.T': 'Nissan Motor Co., Ltd.',
    '7261.T': 'Mazda Motor Corporation',
    '7269.T': 'Suzuki Motor Corporation',
    '7270.T': 'Subaru Corporation',
    '7733.T': 'Olympus Corporation',
    '7751.T': 'Canon Inc.',
    '7832.T': 'Bandai Namco Holdings Inc.',
    '7951.T': 'Yamaha Corporation',
    '8015.T': 'Toyota Tsusho Corporation',
    '8253.T': 'Credit Saison Co., Ltd.',
    '8308.T': 'Resona Holdings, Inc.',
    '8309.T': 'Sumitomo Miitsui Trust Holdings, Inc.',
    '8331.T': 'The Chiba Bank, Ltd.',
    '8354.T': 'Fukuoka Financial Group, Inc.',
    '8410.T': 'Seven Bank, Ltd.',
    '8591.T': 'Orix Corporation',
    '8593.T': 'Mitsubishi HC Capital Inc.',
    '8630.T': 'Sompo Holdings, Inc.',
    '8725.T': 'MS&AD Insurance Group Holdings, Inc.',
    '8750.T': 'Dai-ichi Life Holdings, Inc.',
    '8795.T': 'T&D Holdings, Inc.',
    '8830.T': 'Sumitomo Realty & Development Co., Ltd.',
    '9005.T': 'Tokyu Corporation',
    '9007.T': 'Odakyu Electric Railway Co., Ltd.',
    '9008.T': 'Keio Corporation',
    '9009.T': 'Keisei Electric Railway Co., Ltd.',
    '9021.T': 'West Japan Railway Company',
    '9041.T': 'Kintetsu Group Holdings Co., Ltd.',
    '9042.T': 'Hankyu Hanshin Holdings, Inc.',
    '9064.T': 'Yamato Holdings Co., Ltd.',
    '9104.T': 'Mitsui O.S.K. Lines, Ltd.',
    '9107.T': 'Kawasaki Kisen Kaisha, Ltd.',
    '9501.T': 'Tokyo Electric Power Company Holdings, Incorporated',
    '9502.T': 'Chubu Electric Power Company, Incorporated',
    '9503.T': 'The Kansai Electric Power Company, Incorporated',
    '9531.T': 'Tokyo Gas Co., Ltd.',
    '9532.T': 'Osaka Gas Co., Ltd.',
    '9602.T': 'Toho Co., Ltd.',
    '9766.T': 'Konami Group Corporation',
    '9982.T': 'Takihyo Co., Ltd.',

    # --- HONG KONG & CHINA OFFSHORE (Hong Kong Stock Exchange: .HK) ---
    '0700.HK': 'Tencent Holdings Limited',
    '9988.HK': 'Alibaba Group Holding Limited',
    '3690.HK': 'Meituan',
    '0939.HK': 'China Construction Bank Corporation',
    '1398.HK': 'Industrial and Commercial Bank of China Limited',
    '1211.HK': 'BYD Company Limited',
    '0857.HK': 'PetroChina Company Limited',
    '3988.HK': 'Bank of China Limited',
    '2318.HK': 'Ping An Insurance (Group) Company of China, Ltd.',
    '0388.HK': 'Hong Kong Exchanges and Clearing Limited',
    '0883.HK': 'CNOOC Limited',
    '0941.HK': 'China Mobile Limited',
    '1088.HK': 'China Shenhua Energy Company Limited',
    '1658.HK': 'Postal Savings Bank of China Co., Ltd.',
    '1810.HK': 'Xiaomi Corporation',
    '2015.HK': 'Li Auto Inc.',
    '2331.HK': 'Li Ning Company Limited',
    '2628.HK': 'China Life Insurance Company Limited',
    '3968.HK': 'China Merchants Bank Co., Ltd.',
    '0001.HK': 'CK Hutchison Holdings Limited',
    '0002.HK': 'CLP Holdings Limited',
    '0003.HK': 'The Hong Kong and China Gas Company Limited',
    '0005.HK': 'HSBC Holdings plc',
    '0006.HK': 'Power Assets Holdings Limited',
    '0011.HK': 'Hang Seng Bank Limited',
    '0012.HK': 'Henderson Land Development Company Limited',
    '0016.HK': 'Sun Hung Kai Properties Limited',
    '0017.HK': 'New World Development Company Limited',
    '0027.HK': 'Galaxy Entertainment Group Limited',
    '0066.HK': 'MTR Corporation Limited',
    '0083.HK': 'Sino Land Company Limited',
    '0101.HK': 'Hang Lung Properties Limited',
    '0151.HK': 'Want Want China Holdings Limited',
    '0175.HK': 'Geely Automobile Holdings Limited',
    '0267.HK': 'CITIC Limited',
    '0288.HK': 'WH Group Limited',
    '0291.HK': 'China Resources Beer (Holdings) Company Limited',
    '0322.HK': 'Tingyi (Cayman Islands) Holding Corp.',
    '0669.HK': 'Techtronic Industries Company Limited',
    '0688.HK': 'China Overseas Land & Investment Limited',
    '0762.HK': 'China Unicom (Hong Kong) Limited',
    '0823.HK': 'Link Real Estate Investment Trust',
    '0868.HK': 'Xinyi Glass Holdings Limited',
    '0914.HK': 'Anhui Conch Cement Company Limited',
    '0922.HK': 'Anhui Jianghuai Automobile Group Corp., Ltd.',
    '0960.HK': 'Longfor Group Holdings Limited',
    '0968.HK': 'Xinyi Solar Holdings Limited',
    '0992.HK': 'Lenovo Group Limited',
    '1038.HK': 'CK Infrastructure Holdings Limited',
    '1044.HK': 'Hengan International Group Company Limited',
    '1093.HK': 'CSPC Pharmaceutical Group Limited',
    '1109.HK': 'China Resources Land Limited',
    '1113.HK': 'CK Asset Holdings Limited',
    '1177.HK': 'Sino Biopharmaceutical Limited',
    '1199.HK': 'COSCO SHIPPING Ports Limited',
    '1209.HK': 'China Resources Mixc Lifestyle Services Limited',
    '1288.HK': 'Agricultural Bank of China Limited',
    '1378.HK': 'China Hongqiao Group Limited',
    '1928.HK': 'Sands China Ltd.',
    '1929.HK': 'Chow Tai Fook Jewellery Group Limited',
    '2020.HK': 'ANTA Sports Products Limited',
    '2269.HK': 'WuXi Biologics (Cayman) Inc.',
    '2313.HK': 'Shenzhou International Group Holdings Limited',
    '2319.HK': 'China Mengniu Dairy Company Limited',
    '2382.HK': 'Sunny Optical Technology (Group) Company Limited',
    '2388.HK': 'BOC Hong Kong (Holdings) Limited',
    '2600.HK': 'Aluminum Corporation of China Limited',
    '2688.HK': 'ENN Energy Holdings Limited',
    '2899.HK': 'Zijin Mining Group Co., Ltd.',
    '3311.HK': 'China State Construction International Holdings Limited',
    '3323.HK': 'China National Building Material Company Limited',
    '6088.HK': 'FIT Hon Teng Limited',
    '6160.HK': 'Cansino Biologics Inc.',
    '6618.HK': 'JD Health International Inc.',
    '6690.HK': 'Haier Smart Home Co., Ltd.',
    '6862.HK': 'Haidilao International Holding Ltd.',
    '9618.HK': 'JD.com, Inc.',
    '9633.HK': 'Nongfu Spring Co., Ltd.',
    '9888.HK': 'Baidu, Inc.',
    '9999.HK': 'NetEase, Inc.',

    # --- MAINLAND CHINA ON-SHORE (Shanghai: .SS & Shenzhen: .SZ) ---
    '600519.SS': 'Kweichow Moutai Co., Ltd.',
    '601398.SS': 'Industrial and Commercial Bank of China Limited',
    '601857.SS': 'PetroChina Company Limited',
    '601288.SS': 'Agricultural Bank of China Limited',
    '601988.SS': 'Bank of China Limited',
    '600036.SS': 'China Merchants Bank Co., Ltd.',
    '601628.SS': 'China Life Insurance Company Limited',
    '601088.SS': 'China Shenhua Energy Company Limited',
    '600900.SS': 'China Yangtze Power Co., Ltd.',
    '601318.SS': 'Ping An Insurance (Group) Company of China, Ltd.',
    '601166.SS': 'Industrial Bank Co., Ltd.',
    '600030.SS': 'CITIC Securities Company Limited',
    '601328.SS': 'Bank of Communications Co., Ltd.',
    '600016.SS': 'China Minsheng Banking Corp., Ltd.',
    '601939.SS': 'China Construction Bank Corporation',
    '601998.SS': 'China Citic Bank Corporation Limited',
    '601818.SS': 'China Everbright Bank Company Limited',
    '601006.SS': 'Daqin Railway Co., Ltd.',
    '600000.SS': 'Shanghai Pudong Development Bank Co., Ltd.',
    '600019.SS': 'Baoshan Iron & Steel Co., Ltd.',
    '600028.SS': 'China Petroleum & Chemical Corporation',
    '600048.SS': 'Poly Developments and Holdings Group Co., Ltd.',
    '600104.SS': 'SAIC Motor Corporation Limited',
    '600276.SS': 'Jiangsu Hengrui Pharmaceuticals Co., Ltd.',
    '600309.SS': 'Wanhua Chemical Group Co., Ltd.',
    '600406.SS': 'NARI Technology Co., Ltd.',
    '600585.SS': 'Anhui Conch Cement Company Limited',
    '600690.SS': 'Haier Smart Home Co., Ltd.',
    '600809.SS': 'Shanxi Xinghuacun Fen Wine Factory Co., Ltd.',
    '600887.SS': 'Inner Mongolia Yili Industrial Group Co., Ltd.',
    '601111.SS': 'Air China Limited',
    '601138.SS': 'Foxconn Industrial Internet Co., Ltd.',
    '601169.SS': 'Bank of Beijing Co., Ltd.',
    '601211.SS': 'Guotai Junan Securities Co., Ltd.',
    '601229.SS': 'Bank of Shanghai Co., Ltd.',
    '601336.SS': 'New China Life Insurance Company Ltd.',
    '601390.SS': 'China Railway Group Limited',
    '601601.SS': 'China Pacific Insurance (Group) Co., Ltd.',
    '601618.SS': 'Metallurgical Corporation of China Ltd.',
    '601658.SS': 'Postal Savings Bank of China Co., Ltd.',
    '601668.SS': 'China State Construction Engineering Corporation Limited',
    '601688.SS': 'Huatai Securities Co., Ltd.',
    '601728.SS': 'China Telecom Corporation Limited',
    '601766.SS': 'CRRC Corporation Limited',
    '601800.SS': 'China Communications Construction Company Limited',
    '601816.SS': '斬京銀行 (Bank of Nanjing Co., Ltd.)',
    '601888.SS': 'China Tourism Duty Free Corporation Limited',
    '601898.SS': 'China Coal Energy Company Limited',
    '601899.SS': 'Zijin Mining Group Co., Ltd.',
    '601919.SS': 'COSCO SHIPPING Holdings Co., Ltd.',
    '000001.SZ': 'Ping An Bank Co., Ltd.',
    '000002.SZ': 'China Vanke Co., Ltd.',
    '000333.SZ': 'Midea Group Co., Ltd.',
    '000568.SZ': 'Luzhou Laojiao Co., Ltd.',
    '000651.SZ': 'Gree Electric Appliances, Inc. of Zhuhai',
    '000725.SZ': 'BOE Technology Group Co., Ltd.',
    '000768.SZ': 'AVIC Xi\'an Aircraft Industry Group Company Ltd.',
    '000792.SZ': 'Qinghai Salt Lake Industry Co., Ltd.',
    '000858.SZ': 'Wuliangye Yibin Co., Ltd.',
    '002027.SZ': 'Focus Media Information Technology Co., Ltd.',
    '002142.SZ': 'Bank of Ningbo Co., Ltd.',
    '002241.SZ': 'GoerTek Inc.',
    '002304.SZ': 'Jiangsu Yanghe Brewery Joint-Stock Co., Ltd.',
    '002352.SZ': 'S.F. Holding Co., Ltd.',
    '002415.SZ': 'Hangzhou Hikvision Digital Technology Co., Ltd.',
    '002459.SZ': 'EVE Energy Co., Ltd.',
    '002475.SZ': 'Luxshare Precision Industry Co., Ltd.',
    '002594.SZ': 'BYD Company Limited',
    '002714.SZ': 'Muyuan Foods Co., Ltd.',
    '002736.SZ': 'Guosen Securities Co., Ltd.',
    '300015.SZ': 'Aier Eye Hospital Group Co., Ltd.',
    '300059.SZ': 'East Money Information Co., Ltd.',
    '300122.SZ': 'Chongqing Zhifei Biological Products Co., Ltd.',
    '300124.SZ': 'Inovance Technology Co., Ltd.',
    '300274.SZ': 'Sungrow Power Supply Co., Ltd.',
    '300413.SZ': 'Mango Excellent Media Co., Ltd.',
    '300498.SZ': 'Wens Foodstuffs Group Co., Ltd.',
    '300750.SZ': 'Contemporary Amperex Technology Co., Limited (CATL)',
    '300760.SZ': 'Shenzhen Mindray Bio-Medical Electronics Co., Ltd.',
    '002460.SZ': 'Ganfeng Lithium Group Co., Ltd.',

    # --- INDIA (National Stock Exchange: .NS) ---
    'RELIANCE.NS': 'Reliance Industries Limited',
    'TCS.NS': 'Tata Consultancy Services Limited',
    'HDFCBANK.NS': 'HDFC Bank Limited',
    'ICICIBANK.NS': 'ICICI Bank Limited',
    'BHARTIARTL.NS': 'Bharti Airtel Limited',
    'INFY.NS': 'Infosys Limited',
    'SBIN.NS': 'State Bank of India',
    'LIC.NS': 'Life Insurance Corporation of India',
    'ITC.NS': 'ITC Limited',
    'HINDUNILVR.NS': 'Hindustan Unilever Limited',
    'LT.NS': 'Larsen & Toubro Limited',
    'HCLTECH.NS': 'HCL Technologies Limited',
    'BAJFINANCE.NS': 'Bajaj Finance Limited',
    'SUNPHARMA.NS': 'Sun Pharmaceutical Industries Limited',
    'MARUTI.NS': 'Maruti Suzuki India Limited',
    'TATAMOTORS.NS': 'Tata Motors Limited',
    'KOTAKBANK.NS': 'Kotak Mahindra Bank Limited',
    'AXISBANK.NS': 'Axis Bank Limited',
    'NTPC.NS': 'NTPC Limited',
    'ONGC.NS': 'Oil and Natural Gas Corporation Limited',
    'COALINDIA.NS': 'Coal India Limited',
    'ADANIENT.NS': 'Adani Enterprises Limited',
    'ADANIGREEN.NS': 'Adani Green Energy Limited',
    'ADANIPORTS.NS': 'Adani Ports and Special Economic Zone Limited',
    'ADANIPOWER.NS': 'Adani Power Limited',
    'TITAN.NS': 'Titan Company Limited',
    'ULTRACEMCO.NS': 'UltraTech Cement Limited',
    'ASIANPAINT.NS': 'Asian Paints Limited',
    'DMART.NS': 'Avenue Supermarts Limited',
    'BAJAJFINSV.NS': 'Bajaj Finserv Limited',
    'WIPRO.NS': 'Wipro Limited',
    'NESTLEIND.NS': 'Nestle India Limited',
    'JSWSSTEEL.NS': 'JSW Steel Limited',
    'M&M.NS': 'Mahindra & Mahindra Limited',
    'GRASIM.NS': 'Grasim Industries Limited',
    'TATASTEEL.NS': 'Tata Steel Limited',
    'POWERGRID.NS': 'Power Grid Corporation of India Limited',
    'HINDALCO.NS': 'Hindalco Industries Limited',
    'TECHM.NS': 'Tech Mahindra Limited',
    'CIPLA.NS': 'Cipla Limited',
    'DRREDDY.NS': 'Dr. Reddy\'s Laboratories Limited',
    'SBILIFE.NS': 'SBI Life Insurance Company Limited',
    'HDFCLIFE.NS': 'HDFC Life Insurance Company Limited',
    'BPCL.NS': 'Bharat Petroleum Corporation Limited',
    'IOC.NS': 'Indian Oil Corporation Limited',
    'GAIL.NS': 'GAIL (India) Limited',
    'BRITANNIA.NS': 'Britannia Industries Limited',
    'EICHERMOT.NS': 'Eicher Motors Limited',
    'INDUSINDBK.NS': 'IndusInd Bank Limited',
    'DIVISLAB.NS': 'Divi\'s Laboratories Limited',
    'BAJAJ-AUTO.NS': 'Bajaj Auto Limited',
    'APOLLOHOSP.NS': 'Apollo Hospitals Enterprise Limited',
    'VBL.NS': 'Varun Beverages Limited',
    'SHREECEM.NS': 'Shree Cement Limited',
    'TATACONSUM.NS': 'Tata Consumer Products Limited',
    'JIOFIN.NS': 'Jio Financial Services Limited',
    'CHOLAMANDM.NS': 'Cholamandalam Investment and Finance Company Limited',
    'DLF.NS': 'DLF Limited',
    'ZOMATO.NS': 'Zomato Limited',
    'TRENT.NS': 'Trent Limited',
    'RECLTD.NS': 'REC Limited',
    'PFC.NS': 'Power Finance Corporation Limited',
    'GODREJCP.NS': 'Godrej Consumer Products Limited',
    'HEROMOTOCO.NS': 'Hero MotoCorp Limited',
    'LTIM.NS': 'LTIMindtree Limited',
    'BEL.NS': 'Bharat Electronics Limited',
    'HAL.NS': 'Hindustan Aeronautics Limited',
    'SIEMENS.NS': 'Siemens Limited',
    'ABB.NS': 'ABB India Limited',
    'CUMMINSIND.NS': 'Cummins India Limited',
    'PIDILITIND.NS': 'Pidilite Industries Limited',
    'MARICO.NS': 'Marico Limited',
    'BERGEPAINT.NS': 'Berger Paints India Limited',
    'DABUR.NS': 'Dabur India Limited',
    'COLPAL.NS': 'Colgate-Palmolive (India) Limited',
    'UPL.NS': 'UPL Limited',
    'SRF.NS': 'SRF Limited',
    'AMBUJACEM.NS': 'Ambuja Cements Limited',
    'ACC.NS': 'ACC Limited',
    'MUTHOOTFIN.NS': 'Muthoot Finance Limited',
    'PNB.NS': 'Punjab National Bank',
    'BOB.NS': 'Bank of Baroda',
    'CANBK.NS': 'Canara Bank',
    'IDBI.NS': 'IDBI Bank Limited',
    'IOB.NS': 'Indian Overseas Bank',
    'UNIONBANK.NS': 'Union Bank of India',
    'CENTRALBK.NS': 'Central Bank of India',
    'AUROPHARMA.NS': 'Aurobindo Pharma Limited',
    'LUPIN.NS': 'Lupin Limited',
    'BIOCON.NS': 'Biocon Limited',

    # --- TAIWAN (Taiwan Stock Exchange: .TW) ---
    '2330.TW': 'Taiwan Semiconductor Manufacturing Company Limited (TSMC)',
    '2317.TW': 'Hon Hai Precision Industry Co., Ltd. (Foxconn)',
    '2454.TW': 'MediaTek Inc.',
    '2308.TW': 'Delta Electronics, Inc.',
    '2881.TW': 'Fubon Financial Holding Co., Ltd.',
    '2882.TW': 'Cathay Financial Holding Co., Ltd.',
    '2382.TW': 'Quanta Computer Inc.',
    '2412.TW': 'Chunghwa Telecom Co., Ltd.',
    '2303.TW': 'United Microelectronics Corporation (UMC)',
    '2891.TW': 'CTBC Financial Holding Co., Ltd.',
    '1301.TW': 'Formosa Plastics Corporation',
    '1303.TW': 'Nan Ya Plastics Corporation',
    '1326.TW': 'Formosa Chemicals & Fibre Corporation',
    '6505.TW': 'Formosa Petrochemical Corporation',
    '2002.TW': 'China Steel Corporation',
    '2886.TW': 'Mega Financial Holding Co., Ltd.',
    '2885.TW': 'Yuanta Financial Holding Co., Ltd.',
    '3008.TW': 'Largan Precision Co., Ltd.',
    '2379.TW': 'Realtek Semiconductor Corp.',
    '3711.TW': 'ASE Technology Holding Co., Ltd.',
    '2884.TW': 'E.SUN Financial Holding Co., Ltd.',
    '2892.TW': 'First Financial Holding Co., Ltd.',
    '5880.TW': 'Taiwan Cooperative Financial Holding Co., Ltd.',
    '2890.TW': 'Sinopac Financial Holdings Co., Ltd.',
    '2883.TW': 'China Development Financial Holding Corp.',
    '2357.TW': 'ASUSTeK Computer Inc.',
    '4904.TW': 'Far EasTone Telecommunications Co., Ltd.',
    '3045.TW': 'Taiwan Mobile Co., Ltd.',
    '2408.TW': 'Nanya Technology Corporation',
    '2327.TW': 'Yageo Corporation',
    '2603.TW': 'Evergreen Marine Corporation (Taiwan) Ltd.',
    '2609.TW': 'Yang Ming Marine Transport Corporation',
    '2615.TW': 'Wan Hai Lines Ltd.',
    '2301.TW': 'Lite-On Technology Corporation',
    '2395.TW': 'Advantech Co., Ltd.',
    '3231.TW': 'Wistron Corporation',
    '2356.TW': 'Inventec Corporation',
    '2409.TW': 'AUO Corporation',
    '3481.TW': 'Innolux Corporation',
    '1101.TW': 'Taiwan Cement Corporation',
    '1102.TW': 'Asia Cement Corporation',
    '1402.TW': 'Far Eastern New Century Corporation',
    '2105.TW': 'Cheng Shin Rubber Ind. Co., Ltd.',
    '9904.TW': 'Pou Chen Corporation',
    '2912.TW': 'President Chain Store Corporation',
    '5876.TW': 'Shanghai Commercial & Savings Bank, Ltd.',
    '2801.TW': 'Chang Hwa Commercial Bank, Ltd.',
    '2834.TW': 'Taiwan Business Bank',
    '6005.TW': 'Capital Securities Corporation',
    '2887.TW': 'Taishin Financial Holding Co., Ltd.',

    # --- SOUTH KOREA (Korea Exchange: .KS) ---
    '005930.KS': 'Samsung Electronics Co., Ltd.',
    '000660.KS': 'SK Hynix Inc.',
    '373220.KS': 'LG Energy Solution, Ltd.',
    '005380.KS': 'Hyundai Motor Company',
    '000270.KS': 'Kia Corporation',
    '207940.KS': 'Samsung Biologics Co., Ltd.',
    '068270.KS': 'Celltrion, Inc.',
    '035420.KS': 'NAVER Corporation',
    '051910.KS': 'LG Chem, Ltd.',
    '006400.KS': 'Samsung SDI Co., Ltd.',
    '005490.KS': 'POSCO Holdings Inc.',
    '035720.KS': 'Kakao Corp.',
    '105560.KS': 'KB Financial Group Inc.',
    '055550.KS': 'Shinhan Financial Group Co., Ltd.',
    '012330.KS': 'Hyundai Mobis Co., Ltd.',
    '003550.KS': 'LG Corp.',
    '032830.KS': 'Samsung Life Insurance Co., Ltd.',
    '096770.KS': 'SK Innovation Co., Ltd.',
    '015760.KS': 'Korea Electric Power Corporation',
    '000810.KS': 'Samsung Fire & Marine Insurance Co., Ltd.',
    '086790.KS': 'Hana Financial Group Inc.',
    '018260.KS': 'Samsung SDS Co., Ltd.',
    '010140.KS': 'Samsung Heavy Industries Co., Ltd.',
    '033780.KS': 'KT&G Corporation',
    '009150.KS': 'Samsung Electro-Mechanics Co., Ltd.',
    '011170.KS': 'Lotte Chemical Corporation',
    '000720.KS': 'Hyundai Engineering & Construction Co., Ltd.',
    '010950.KS': 'S-Oil Corporation',
    '034220.KS': 'LG Display Co., Ltd.',
    '003670.KS': 'Pohang Coated Steel Co., Ltd. (POSCO C&C)',
    '086280.KS': 'Hyundai Glovis Co., Ltd.',
    '005830.KS': 'DB Insurance Co., Ltd.',
    '011780.KS': 'Kumho Petrochemical Co., Ltd.',
    '034730.KS': 'SK Inc.',
    '017670.KS': 'SK Telecom Co., Ltd.',
    '004020.KS': 'Hyundai Steel Company',
    '097950.KS': 'CJ CheilJedang Corp.',
    '251270.KS': 'Netmarble Corporation',
    '028260.KS': 'Samsung C&T Corporation',
    '323410.KS': 'Kakao Bank Corp.',
    '302440.KS': 'SK Bioscience Co., Ltd.',
    '316140.KS': 'Woori Financial Group Inc.',
    '047050.KS': 'Daewoo Shipbuilding & Marine Engineering Co., Ltd. (Hanwha Ocean)',
    '009830.KS': 'Hanwha Aerospace Co., Ltd.',
    '010130.KS': 'Korea Zinc Co., Ltd.',
    '001040.KS': 'CJ Corporation',
    '024110.KS': 'Industrial Bank of Korea',
    '036570.KS': 'NCSoft Corporation',
    '011200.KS': 'HMM Co., Ltd.',
    '003490.KS': 'Korean Air Lines Co., Ltd.',

    # --- ASEAN (Singapore: .SI, Indonesia: .JK, Malaysia: .KL, Thailand: .BK) ---
    'D05.SI': 'DBS Group Holdings Ltd',
    'O39.SI': 'Oversea-Chinese Banking Corporation Limited',
    'U11.SI': 'United Overseas Bank Limited',
    'Z74.SI': 'Singapore Telecommunications Limited (Singtel)',
    'C52.SI': 'ComfortDelGro Corporation Limited',
    'BS6.SI': 'Yangzijiang Shipbuilding (Holdings) Ltd.',
    'J36.SI': 'Jardine Matheson Holdings Limited',
    'G13.SI': 'Genting Singapore Limited',
    'T39.SI': 'Sembcorp Industries Ltd',
    'BN4.SI': 'Keppel Ltd.',
    'BBCA.JK': 'PT Bank Central Asia Tbk',
    'BBRI.JK': 'PT Bank Rakyat Indonesia (Persero) Tbk',
    'TLKM.JK': 'PT Telkom Indonesia (Persero) Tbk',
    'BMRI.JK': 'PT Bank Mandiri (Persero) Tbk',
    'ASII.JK': 'PT Astra International Tbk',
    'BYAN.JK': 'PT Bayan Resources Tbk',
    'BBNI.JK': 'PT Bank Negara Indonesia (Persero) Tbk',
    'UNVR.JK': 'PT Unilever Indonesia Tbk',
    'AMRT.JK': 'PT Sumber Alfaria Trijaya Tbk',
    'GOTO.JK': 'PT GoTo Gojek Tokopedia Tbk',
    '1155.KL': 'Malayan Banking Berhad (Maybank)',
    '1023.KL': 'CIMB Group Holdings Berhad',
    '5184.KL': 'LPI Capital Bhd',
    '1295.KL': 'Public Bank Berhad',
    '6888.KL': 'Axiata Group Berhad',
    '4011.KL': 'Telekom Malaysia Berhad',
    '5225.KL': 'IHH Healthcare Berhad',
    '1066.KL': 'RHB Bank Berhad',
    '4707.KL': 'Nestle (Malaysia) Berhad',
    '5183.KL': 'Petronas Chemicals Group Berhad',
    'PTT.BK': 'PTT Public Company Limited',
    'DELTA.BK': 'Delta Electronics (Thailand) Public Company Limited',
    'ADVANC.BK': 'Advanced Info Service Public Company Limited',
    'AOT.BK': 'Airports of Thailand Public Company Limited',
    'GULF.BK': 'Gulf Energy Development Public Company Limited',
    'CPALL.BK': 'CP ALL Public Company Limited',
    'BDMS.BK': 'Bangkok Dusit Medical Services Public Company Limited',
    'SCC.BK': 'The Siam Cement Public Company Limited',
    'PTTEP.BK': 'PTT Exploration and Production Public Company Limited',
    'SCB.BK': 'SCB X Public Company Limited'
}
