import yfinance as yf
import pandas as pd
import requests
from datetime import datetime, timedelta
import os

ticker_germany = {
    'SAP.DE': 'SAP SE',
    'SIE.DE': 'Siemens AG',
    'ALV.DE': 'Allianz SE',
    'DTE.DE': 'Deutsche Telekom AG',
    'ENR.DE': 'Siemens Energy AG',
    'IFX.DE': 'Infineon Technologies AG',
    'RHM.DE': 'Rheinmetall AG',
    'DHL.DE': 'DHL Group',
    'MRK.DE': 'Merck KGaA',
    'MUV2.DE': 'Münchener Rückversicherungs-Gesellschaft AG',
    'DBK.DE': 'Deutsche Bank AG',
    'MBG.DE': 'Mercedes-Benz Group AG',
    'VOW3.DE': 'Volkswagen AG',
    'EOAN.DE': 'E.ON SE',
    'BMW.DE': 'Bayerische Motoren Werke AG',
    'BAS.DE': 'BASF SE',
    'DB1.DE': 'Deutsche Börse AG',
    'P911.DE': 'Dr. Ing. h.c. F. Porsche AG',
    'RWE.DE': 'RWE AG',
    'SHL.DE': 'Siemens Healthineers AG',
    'CBK.DE': 'Commerzbank AG',
    'HEI.DE': 'Heidelberg Materials AG',
    'DTG.DE': 'Daimler Truck Holding AG',
    'ADS.DE': 'Adidas AG',
    'FRE.DE': 'Fresenius SE & Co. KGaA',
    'VNA.DE': 'Vonovia SE',
    'BEI.DE': 'Beiersdorf AG',
    'CON.DE': 'Continental AG',
    'SY1.DE': 'Symrise AG',
    'QIA.DE': 'Qiagen N.V.',
    'HNR1.DE': 'Hannover Rück SE',
    'MTX.DE': 'MTU Aero Engines AG',
    'HEN3.DE': 'Henkel AG & Co. KGaA',
    'SRT3.DE': 'Sartorius AG',
    'ZAL.DE': 'Zalando SE',
    'FME.DE': 'Fresenius Medical Care AG & Co. KGaA',
    'G24.DE': 'GRENKE AG',
    'PUM.DE': 'PUMA SE',
    'EVK.DE': 'Evonik Industries AG',
    'WCH.DE': 'Wacker Chemie AG',
    'LEG.DE': 'LEG Immobilien SE',
    'KBX.DE': 'Knorr-Bremse AG',
    'HOT.DE': 'Hochtief AG',
    'AIXA.DE': 'Aixtron SE',
    'AM3D.DE': 'Amadeus Fire AG',
    'NDX1.DE': 'Nordex SE',
    'AFX.DE': 'Carl Zeiss Meditec AG',
    'HFG.DE': 'HelloFresh SE',
    'BOSS.DE': 'HUGO BOSS AG',
    'FRA.DE': 'Fraport AG',
    'EVD.DE': 'Evotec SE',
    'TUI1.DE': 'TUI AG',
    'LHA.DE': 'Deutsche Lufthansa AG',
    'JUN3.DE': 'Jungheinrich AG',
    'G1A.DE': 'GEA Group AG',
    'SDF.DE': 'K+S AG',
    'TAG.DE': 'TAG Immobilien AG',
    'SGL.DE': 'SGL Carbon SE',
    'BC8.DE': 'Aroundtown SA',
    'HAG.DE': 'Hamburger Hafen und Logistik AG',
    'GYC.DE': 'GFT Technologies SE',
    'FPE3.DE': 'Ferratum Oyj (Multitude SE)',
    'SMHN.DE': 'SMT Scharf AG',
    'NDA.DE': 'Aurubis AG',
    'GLJ.DE': 'Global Fashion Group S.A.',
    'PNE3.DE': 'PNE AG',
    'O2D.DE': 'Telefónica Deutschland Holding AG',
    'NEM.DE': 'Nemetschek SE',
    'GFT.DE': 'GFT Technologies SE',
    'HDD.DE': 'Hamburger Hafen und Logistik AG',
    'DUE.DE': 'Dürr AG',
    'CEC.DE': 'Ceconomy AG',
    'ARL.DE': 'Aareal Bank AG',
    'B4B.DE': 'Borussia Dortmund GmbH & Co. KGaA',
    '1U1.DE': '1&1 AG',
    'RAA.DE': 'Rational AG',
    'HYQ.DE': 'Hypoport SE',
    'DWNI.DE': 'Deutsche Wohnen SE',
    'DHER.DE': 'Delivery Hero SE',
    'EVT.DE': 'Evotec SE',
    'BVB.DE': 'Borussia Dortmund GmbH & Co. KGaA',
    'SOW.DE': 'Software AG',
    'PFV.DE': 'Pfeiffer Vacuum Technology AG',
    'WAF.DE': 'Siltronic AG',
    'SAX.DE': 'Stada Arzneimittel AG',
    'VTSC.DE': 'Vitesco Technologies Group AG',
    'TLX.DE': 'Talanx AG',
    'EUZ.DE': 'Euromicron AG',
    'GXI.DE': 'Gerresheimer AG',
    'AOX.DE': 'Alstria Office REIT-AG',
    'COK.DE': 'CompuGroup Medical SE & Co. KGaA',
    'GMM.DE': 'Grammer AG',
    'SANT.DE': 'Santa Fe Group A/S',
    'ADV.DE': 'Adva Optical Networking SE',
    'UTDI.DE': 'United Internet AG',
    'SXT.DE': 'Sensirion Holding AG',
    'MLP.DE': 'MLP SE',
    'KRN.DE': 'Krones AG',
    'IVU.DE': 'IVU Traffic Technologies AG',
    'ZIL2.DE': 'Zalando SE',
    'BYW6.DE': 'BayWa AG',
    'BWB.DE': 'BWT Aktiengesellschaft',
    'ECV.DE': 'Eckert & Ziegler AG',
    'AAQ.DE': 'aamadoo AG',
    'TTR1.DE': 'TeamViewer SE',
    'D6H.DE': 'Deutsche Beteiligungs AG',
    'VBK.DE': 'Volksbank AG',
    'STO3.DE': 'Stöbich AG',
    'FORG.DE': 'Forterra plc',
    'PN3.DE': 'PNE AG',
    'PBB.DE': 'Deutsche Pfandbriefbank AG',
    'HBH.DE': 'H&R AG',
    'ELG.DE': 'Elmos Semiconductor SE',
    'WAS.DE': 'WashTec AG',
    'PFT.DE': 'Pfandbriefbank AG',
    'MSLL.DE': 'Maschinenfabrik Berthold Hermle AG',
    'CBB.DE': 'Cewe Stiftung & Co. KGaA',
    'GLA.DE': 'GFT Technologies SE',
    'CWC.DE': 'Cancom SE',
    'MUM.DE': 'Muehlhan AG',
    'FIE.DE': 'Fielmann AG',
    'B5A.DE': 'BayWa AG',
    'BSL.DE': 'Basler AG',
    'ACT.DE': 'Actinium Pharmaceuticals, Inc.',
    'GEC.DE': 'Gerresheimer AG',
    'SYZ.DE': 'SYZYGY AG',
    'BCP.DE': 'Bayer CropScience AG',
    'VTW.DE': 'Vitasun AG',
    'M7U.DE': 'M7 Real Estate',
    'SMT.DE': 'SMT Scharf AG',
    'KCO.DE': 'Klöckner & Co SE',
    'BOS.DE': 'Bossard Holding AG',
    'VIB.DE': 'VIB Vermögen AG',
    'DRE.DE': 'Drägerwerk AG & Co. KGaA',
    'NXG.DE': 'Nexus AG',
    'O1BC.DE': '1&1 AG',
    'KWS.DE': 'KWS Saat SE & Co. KGaA',
    'LHS.DE': 'LHS Telekommunikation',
    'AAD.DE': 'Adva Optical Networking SE',
    'OHB.DE': 'OHB SE',
    'MFT.DE': 'Manz AG',
    'VT9.DE': 'Varta AG',
    'HLE.DE': 'Heidelberger Druckmaschinen AG',
    'SKB.DE': 'Südzucker AG',
    'CAP.DE': 'Caparol AG',
    'SLT.DE': 'Siltronic AG',
    'TNH.DE': 'TUI AG',
    'HHK.DE': 'H&R AG',
    'CLK.DE': 'Carl Zeiss Meditec AG',
    'VAB.DE': 'Varta AG',
    'INH.DE': 'Innate Pharma SA',
    'IFA.DE': 'IFA Hotel & Touristik AG',
    'BYW.DE': 'BayWa AG',
    'SHF.DE': 'Shiftex AG',
    'DBAN.DE': 'Deutsche Bahn AG',
    'NWRK.DE': 'Network AG',
    'MDO.DE': 'Medion AG',
    'PVE.DE': 'PNE AG',
    'IIG.DE': 'IIG AG',
    'SNG.DE': 'SGL Carbon SE',
    'AR4.DE': 'Aroundtown SA',
    'SQU.DE': 'Squer AG',
    'EXX.DE': 'iShares STOXX Europe 600',
    'YOC.DE': 'YOC AG',
    'F3C.DE': 'FCR Immobilien AG',
    'HM7.DE': 'Heidelberg Materials AG',
    'MUX.DE': 'Muehlhan AG',
    'E2N.DE': 'E2N AG',
    'KMT.DE': 'Klöckner & Co SE',
    'KBC.DE': 'KBC Group NV',
    'TTK.DE': 'TUI AG',
    'ED4.DE': 'E.ON SE',
    'AOF.DE': 'AOF AG',
    'BFSA.DE': 'Bayer AG',
    'BEZ.DE': 'Beiersdorf AG',
    'BIJ.DE': 'Bijou Brigitte AG',
    'GBF.DE': 'Gerresheimer AG',
    'EXSG.DE': 'iShares MSCI Europe ESG',
    'EXSA.DE': 'iShares STOXX Europe 600',
    'ISPA.DE': 'iShares MSCI Europe',
    'EXSD.DE': 'iShares STOXX Europe 600',
    'EXSH.DE': 'iShares STOXX Europe 600',
    'EXSE.DE': 'iShares STOXX Europe 600',
    'EXXU.DE': 'iShares STOXX Europe 600',
    'EXX5.DE': 'iShares STOXX Europe 600',
    'EXXT.DE': 'iShares STOXX Europe 600',
    '1NN.DE': '1&1 AG',
    '1SXP.DE': 'iShares STOXX Europe 600',
    '2GB.DE': '2G Energy AG',
    '2HRA.DE': '2HRA AG',
    '3ITN.DE': '3ITN AG',
    '3SQ1.DE': '3SQ1 AG',
    '4DSD.DE': '4DSD AG',
    '4X0.DE': '4X0 AG',
    '7V0.DE': '7V0 AG',
    '93M1.DE': '93M1 AG',
    'A1OS.DE': 'A1OS AG',
    'A6T.DE': 'A6T AG',
    'A7AH.DE': 'A7AH AG',
    'ACX.DE': 'ACX AG'
}