import yfinance as yf
import pandas as pd
import requests
from datetime import datetime, timedelta
import os

ticker_europe = {
    # France (.PA)
    'MC.PA': 'LVMH Moët Hennessy Louis Vuitton',
    'OR.PA': 'LOréal S.A.',
    'RMS.PA': 'Hermès International',
    'TTE.PA': 'TotalEnergies SE',
    'SAN.PA': 'Sanofi',
    'SU.PA': 'Schneider Electric SE',
    'AI.PA': 'Air Liquide S.A.',
    'AIR.PA': 'Airbus SE',
    'BNP.PA': 'BNP Paribas S.A.',
    'DG.PA': 'Vinci S.A.',
    'CS.PA': 'AXA S.A.',
    'EL.PA': 'EssilorLuxottica',
    'BN.PA': 'Danone S.A.',
    'SAF.PA': 'Safran S.A.',
    'CAP.PA': 'Capgemini SE',
    'ENGI.PA': 'Engie S.A.',
    'SGO.PA': 'Compagnie de Saint-Gobain S.A.',
    'RI.PA': 'Pernod Ricard S.A.',
    'ACA.PA': 'Crédit Agricole S.A.',
    'ORA.PA': 'Orange S.A.',
    'GLE.PA': 'Société Générale S.A.',
    'ML.PA': 'Compagnie Générale des Établissements Michelin',
    'VIE.PA': 'Veolia Environnement S.A.',
    'EN.PA': 'Bouygues S.A.',
    'CA.PA': 'Carrefour S.A.',
    'ALO.PA': 'Alstom S.A.',
    'VIV.PA': 'Vivendi SE',
    'HO.PA': 'Thales S.A.',
    'LR.PA': 'Legrand S.A.',
    'PUB.PA': 'Publicis Groupe S.A.',
    'TEP.PA': 'Teleperformance SE',
    'EDEN.PA': 'Edenred SE',
    'DSY.PA': 'Dassault Systèmes SE',
    'KER.PA': 'Kering S.A.',
    'RNO.PA': 'Renault S.A.',
    'ERF.PA': 'Eurofins Scientific SE',
    'SW.PA': 'Somfy SA',
    'URW.PA': 'Unibail-Rodamco-Westfield SE',
    'AC.PA': 'Accor S.A.',
    'AKE.PA': 'Arkema S.A.',
    'BIM.PA': 'BioMérieux S.A.',
    'BVI.PA': 'Bureau Veritas S.A.',
    'GFC.PA': 'Gecina S.A.',
    'LI.PA': 'Kaufman & Broad S.A.',
    'NEX.PA': 'Nexity S.A.',
    'RCO.PA': 'Rémy Cointreau S.A.',
    'SK.PA': 'Seb S.A.',
    'SOI.PA': 'Soitec S.A.',
    'FRVIA.PA': 'Forvia SE',
    'SCR.PA': 'SCOR SE',

    # Netherlands (.AS)
    'ASML.AS': 'ASML Holding N.V.',
    'INGA.AS': 'ING Groep N.V.',
    'PRX.AS': 'Prosus N.V.',
    'ADYEN.AS': 'Adyen N.V.',
    'WKL.AS': 'Wolters Kluwer N.V.',
    'DSFIR.AS': 'DSM-Firmenich AG',
    'AD.AS': 'Koninklijke Ahold Delhaize N.V.',
    'HEIA.AS': 'Heineken N.V.',
    'PHIA.AS': 'Koninklijke Philips N.V.',
    'AKZA.AS': 'Akzo Nobel N.V.',
    'NN.AS': 'NN Group N.V.',
    'KPN.AS': 'Koninklijke KPN N.V.',
    'ASM.AS': 'ASM International N.V.',
    'RAND.AS': 'Randstad N.V.',
    'AGN.AS': 'Aegon N.V.',
    'LIGHT.AS': 'Signify N.V.',
    'TKWY.AS': 'Just Eat Takeaway.com N.V.',
    'IMCD.AS': 'IMCD N.V.',
    'ABN.AS': 'ABN AMRO Bank N.V.',
    'JDEP.AS': 'JDE Peet\'s N.V.',
    'ARGX.AS': 'argenx SE',
    'OCI.AS': 'OCI N.V.',
    'AALB.AS': 'Aalberts N.V.',
    'FUR.AS': 'Fastned B.V.',
    'VPK.AS': 'Vopak N.V.',
    'SBMO.AS': 'SBM Offshore N.V.',
    'BESI.AS': 'BE Semiconductor Industries N.V.',
    'REN.AS': 'Relx PLC',
    'EXOR.AS': 'Exor N.V.',
    'COR.AS': 'Corbion N.V.',

    # Italy (.MI)
    'ENEL.MI': 'Enel S.p.A.',
    'ENI.MI': 'Eni S.p.A.',
    'ISP.MI': 'Intesa Sanpaolo S.p.A.',
    'UCG.MI': 'UniCredit S.p.A.',
    'RACE.MI': 'Ferrari N.V.',
    'STLAM.MI': 'Stellantis N.V.',
    'G.MI': 'Assicurazioni Generali S.p.A.',
    'SRG.MI': 'Snam S.p.A.',
    'TRN.MI': 'Terna - Rete Elettrica Nazionale S.p.A.',
    'PST.MI': 'Poste Italiane S.p.A.',
    'MONC.MI': 'Moncler S.p.A.',
    'PRY.MI': 'Prysmian S.p.A.',
    'LDO.MI': 'Leonardo S.p.A.',
    'TEN.MI': 'Tenaris S.A.',
    'MB.MI': 'Mediobanca Banca di Credito Finanziario S.p.A.',
    'FBK.MI': 'FinecoBank S.p.A.',
    'BPE.MI': 'BPER Banca S.p.A.',
    'BAMI.MI': 'Banco BPM S.p.A.',
    'NEXI.MI': 'Nexi S.p.A.',
    'TIT.MI': 'Telecom Italia S.p.A.',
    'REC.MI': 'Recordati S.p.A.',
    'AMP.MI': 'Amplifon S.p.A.',
    'DIA.MI': 'DiaSorin S.p.A.',
    'IG.MI': 'Interpump Group S.p.A.',
    'INW.MI': 'Inwit S.p.A.',
    'BC.MI': 'Brunello Cucinelli S.p.A.',
    'SPM.MI': 'Saipem S.p.A.',
    'MT.MI': 'ArcelorMittal S.A.',
    'BRE.MI': 'Brembo S.p.A.',
    'IP.MI': 'ERG S.p.A.',
    'A2A.MI': 'A2A S.p.A.',
    'CPR.MI': 'Capri Holdings Limited',
    'YSY.MI': 'Iveco Group N.V.',
    'PIRC.MI': 'Pirelli & C. S.p.A.',

    # Spain (.MC)
    'IBE.MC': 'Iberdrola S.A.',
    'SAN.MC': 'Banco Santander S.A.',
    'BBVA.MC': 'Banco Bilbao Vizcaya Argentaria S.A.',
    'ITX.MC': 'Industria de Diseño Textil S.A. (Inditex)',
    'AMS.MC': 'Amadeus IT Group S.A.',
    'CABK.MC': 'CaixaBank S.A.',
    'CLNX.MC': 'Cellnex Telecom S.A.',
    'TEF.MC': 'Telefónica S.A.',
    'REP.MC': 'Repsol S.A.',
    'FER.MC': 'Ferrovial SE',
    'AENA.MC': 'Aena S.M.E. S.A.',
    'NTGY.MC': 'Naturgy Energy Group S.A.',
    'RED.MC': 'Redeia Corporación S.A.',
    'ELE.MC': 'Endesa S.A.',
    'GRF.MC': 'Grifols S.A.',
    'ACS.MC': 'ACS, Actividades de Construcción y Servicios S.A.',
    'BKT.MC': 'Bankinter S.A.',
    'ENG.MC': 'Enagás S.A.',
    'MAP.MC': 'Mapfre S.A.',
    'FDR.MC': 'Fluidra S.A.',
    'ANA.MC': 'Acciona S.A.',
    'IDR.MC': 'Indra Sistemas S.A.',
    'SLR.MC': 'Solaria Energía y Medio Ambiente S.A.',
    'COL.MC': 'Inmobiliaria Colonial S.A.R.E.',
    'MRL.MC': 'Merlin Properties SOCIMI S.A.',
    'LOG.MC': 'Logista S.A.',
    'SCYR.MC': 'Sacyr S.A.',
    'UNI.MC': 'Unicaja Banco S.A.',

    # Sweden (.ST)
    'INVE-B.ST': 'Investor AB',
    'ATCO-A.ST': 'Atlas Copco AB',
    'VOLV-B.ST': 'Volvo AB',
    'ERIC-B.ST': 'Telefonaktiebolaget LM Ericsson',
    'HM-B.ST': 'H & M Hennes & Mauritz AB',
    'SEB-A.ST': 'Skandinaviska Enskilda Banken AB',
    'SWED-A.ST': 'Swedbank AB',
    'NDA-SE.ST': 'Nordea Bank Abp',
    'SHB-A.ST': 'Svenska Handelsbanken AB',
    'SAND.ST': 'Sandvik AB',
    'ASSA-B.ST': 'ASSA ABLOY AB',
    'ESSITY-B.ST': 'Essity AB',
    'EVO.ST': 'Evolution AB',
    'HEXA-B.ST': 'Hexagon AB',
    'SKF-B.ST': 'SKF AB',
    'ALFA.ST': 'Alfa Laval AB',
    'BOL.ST': 'Boliden AB',
    'NIBE-B.ST': 'NIBE Industrier AB',
    'TELIA.ST': 'Telia Company AB',
    'EPI-A.ST': 'Epiroc AB',
    'EQT.ST': 'EQT AB',
    'SCA-B.ST': 'Svenska Cellulosa AB SCA',
    'SEC-B.ST': 'Securitas AB',
    'SKA-B.ST': 'Skanska AB',
    'TEL2-B.ST': 'Tele2 AB',
    'GETI-B.ST': 'Getinge AB',
    'CAST.ST': 'Castellum AB',
    'BALD-B.ST': 'Fastighets AB Balder',
    'SAGA-B.ST': 'Sagax AB',
    'EKTA-B.ST': 'Eltel AB',
    'ALIV-SDB.ST': 'Autoliv, Inc.',
    'LUND-B.ST': 'Lundin Mining Corporation',
    'INDT.ST': 'Indutrade AB',
    'LIFCO-B.ST': 'Lifco AB',
    'ADDB.ST': 'Addtech AB',
    'SAAB-B.ST': 'Saab AB',
    'SSAB-A.ST': 'SSAB AB',
    'HOLM-B.ST': 'Holmen AB',

    # Denmark (.CO)
    'NOVO-B.CO': 'Novo Nordisk A/S',
    'DSV.CO': 'DSV A/S',
    'ORSTED.CO': 'Ørsted A/S',
    'VWS.CO': 'Vestas Wind Systems A/S',
    'COLO-B.CO': 'Coloplast A/S',
    'GMAB.CO': 'Genmab A/S',
    'NSIS-B.CO': 'Netcompany Group A/S',
    'MAERSK-B.CO': 'A.P. Møller - Mærsk A/S',
    'CARL-B.CO': 'Carlsberg A/S',
    'DANSKE.CO': 'Danske Bank A/S',
    'JYSK.CO': 'Jyske Bank A/S',
    'DEMANT.CO': 'Demant A/S',
    'GN.CO': 'GN Store Nord A/S',
    'PNDORA.CO': 'Pandora A/S',
    'TRYG.CO': 'Tryg A/S',
    'ISS.CO': 'ISS A/S',
    'RBREW.CO': 'Royal Unibrew A/S',
    'NKT.CO': 'NKT A/S',
    'ROCK-B.CO': 'ROCKWOOL A/S',
    'SYDB.CO': 'Sydbank A/S',

    # Finland (.HE)
    'NDA-FI.HE': 'Nordea Bank Abp',
    'NESTE.HE': 'Neste Oyj',
    'NOKIA.HE': 'Nokia Oyj',
    'SAMPO.HE': 'Sampo Oyj',
    'KNEBV.HE': 'Kone Oyj',
    'UPM.HE': 'UPM-Kymmene Oyj',
    'STEAV.HE': 'Stora Enso Oyj',
    'FORTUM.HE': 'Fortum Oyj',
    'KESKOB.HE': 'Kesko Oyj',
    'ORNBV.HE': 'Orion Oyj',
    'WRT1V.HE': 'Wärtsilä Oyj Abp',
    'METSO.HE': 'Metso Oyj',
    'VALMT.HE': 'Valmet Oyj',
    'ELISA.HE': 'Elisa Oyj',
    'HUH1V.HE': 'Huhtamäki Oyj',
    'KEMIRA.HE': 'Kemira Oyj',
    'CGCIV.HE': 'Cargotec Oyj',
    'TIETO.HE': 'Tietoevry Oyj',
    'QTCOM.HE': 'Qt Group Oyj',
    'METSB.HE': 'Metsä Board Oyj',

    # Belgium (.BR)
    'ABI.BR': 'Anheuser-Busch InBev SA/NV',
    'KBC.BR': 'KBC Group NV',
    'UCB.BR': 'UCB SA',
    'UMI.BR': 'Umicore SA',
    'SOLV.BR': 'Solvay SA',
    'AGS.BR': 'Ageas SA/NV',
    'SYENS.BR': 'Syensqo SA',
    'DIE.BR': 'Dieteren Group',
    'ACKB.BR': 'Ackermans & van Haaren NV',
    'SOF.BR': 'Sofina SA',
    'ELI.BR': 'Elia Group SA',
    'MELE.BR': 'Melexis NV',
    'WDP.BR': 'WDP NV',
    'PROX.BR': 'Proximus NV',
    'LOTB.BR': 'Lotus Bakeries NV',

    # Portugal (.LS)
    'EDP.LS': 'EDP - Energias de Portugal, S.A.',
    'JMT.LS': 'Jerónimo Martins, S.G.P.S., S.A.',
    'GALP.LS': 'Galp Energia, SGPS, S.A.',
    'EDPR.LS': 'EDP Renováveis, S.A.',
    'BCP.LS': 'Banco Comercial Português, S.A.',

    # Austria (.VI)
    'EBS.VI': 'Erste Group Bank AG',
    'OMV.VI': 'OMV AG',
    'VER.VI': 'Verbund AG',
    'RBI.VI': 'Raiffeisen Bank International AG',
    'ANDR.VI': 'Andritz AG',

    # Poland (.WA)
    'PKO.WA': 'Powszechna Kasa Oszczędności Bank Polski S.A.',
    'PKN.WA': 'Polski Koncern Naftowy ORLEN S.A.',
    'PZU.WA': 'Powszechny Zakład Ubezpieczeń S.A.',
    'PEO.WA': 'Bank Pekao S.A.',
    'DNP.WA': 'Dino Polska S.A.'
}