import yfinance as yf
import pandas as pd
import requests
from datetime import datetime, timedelta
import os

ticker_macro = {
    # === I. MONETARY POLICY & CENTRAL BANK BALANCE SHEETS ===
    'FEDFUNDS': 'Effective Federal Funds Rate (Monthly)',
    'DFF': 'Daily Effective Federal Funds Rate',
    'EFFR': 'Effective Federal Funds Rate (Daily Volume-Weighted)',
    'SOFR': 'Secured Overnight Financing Rate',
    'IORB': 'Interest on Reserve Balances',
    'PRIME': 'Bank Prime Loan Rate',
    'WALCL': 'Federal Reserve Total Assets',
    'TREAST': 'U.S. Treasury Securities Held by the Fed',
    'WCURCIR': 'Currency in Circulation',
    'TOTRESNS': 'Total Reserves of Depository Institutions',
    'NONBORRES': 'Non-Borrowed Reserves of Depository Institutions',
    'RRPONTSYD': 'Overnight Reverse Repurchase Agreements',
    'VIXCLS': 'CBOE Volatility Index (FRED Close)',
    'COMPAPER3M': '3-Month Commercial Paper Rate',
    'DFEDTARU': 'Federal Funds Target Range Upper Limit',

    # === II. INFLATION & PRICE INDEX PRESSURES ===
    'CPIAUCSL': 'Consumer Price Index: All Urban Consumers (Headline)',
    'CPILFESL': 'Core CPI (Excludes Food & Energy)',
    'PCEPI': 'Personal Consumption Expenditures Price Index',
    'PCEPILFE': 'Core PCE Price Index',
    'PPIACO': 'Producer Price Index: All Commodities',
    'PPICPE': 'Core PPI',
    'GDPDEF': 'GDP Implicit Price Deflator',
    'CPIENGSL': 'Consumer Price Index: Energy',
    'CPIUFDSL': 'Consumer Price Index: Food',
    'CPIMEDSL': 'Consumer Price Index: Medical Care',
    'CPITRNSL': 'Consumer Price Index: Transportation',
    'EXPINF1YR': '1-Year Expected Inflation',
    'EXPINF5YR': '5-Year Expected Inflation',
    'MICH': 'Univ. of Michigan Inflation Expectations',
    'WPUSI012011': 'PPI: Commodity Commodities',

    # === III. EMPLOYMENT & LABOR MARKET DYNAMICS ===
    'UNRATE': 'U.S. Unemployment Rate',
    'PAYEMS': 'Total Nonfarm Payrolls',
    'ICSA': 'Initial Jobless Claims',
    'CCSA': 'Continued Jobless Claims',
    'JTSJOL': 'JTS Job Openings',
    'JTSHIL': 'JTS Hires Rate',
    'JTSQUL': 'JTS Quits Rate',
    'CIVPART': 'Labor Force Participation Rate',
    'EMRATIO': 'Employment-Population Ratio',
    'U6RATE': 'Total Underemployment Rate',
    'AWHAREMAN': 'Average Weekly Hours: Manufacturing',
    'CES0500000003': 'Average Hourly Earnings: Private Industry',
    'MANEMP': 'Manufacturing Sector Employment',
    'USGOOD': 'All Goods-Producing Employees',
    'SRVPRD': 'All Service-Providing Employees',

    # === IV. NATIONAL ACCOUNTS, PRODUCTION & ORDERS ===
    'GDPC1': 'Real Gross Domestic Product',
    'GDP': 'Nominal Gross Domestic Product',
    'INDPRO': 'Industrial Production Index',
    'TCU': 'Capacity Utilization Rate',
    'DGORDER': 'Manufacturers New Orders: Durable Goods',
    'NEWORDER': 'Manufacturers New Orders: Nondefense Capital Goods',
    'ALTSALES': 'Light Vehicle Retail Sales',
    'RSAFS': 'Advance Retail Sales: Retail & Food Services',
    'PCE': 'Personal Consumption Expenditures',
    'PCEND': 'Personal Consumption Expenditures: Nondurable Goods',
    'PCES': 'Personal Consumption Expenditures: Services',
    'DSPI': 'Disposable Personal Income',
    'A067RX1A020SBEA': 'Real Disposable Personal Income',
    'A939RX0Q048SBEA': 'Real GDP Per Capita',
    'IPBUSED': 'Industrial Production: Business Equipment',

    # === V. YIELD CURVE SPREADS & FIXED INCOME MATURITIES ===
    'T10Y2Y': '10-Year Treasury Minus 2-Year Treasury',
    'T10Y3M': '10-Year Treasury Minus 3-Month Treasury',
    'DGS10': '10-Year Treasury Constant Maturity Yield',
    'DGS2': '2-Year Treasury Constant Maturity Yield',
    'DGS1': '1-Year Treasury Constant Maturity Yield',
    'DGS5': '5-Year Treasury Constant Maturity Yield',
    'DGS30': '30-Year Treasury Constant Maturity Yield',
    'DGS3M': '3-Month Treasury Constant Maturity Yield',
    'BAMLH0A0HYM2': 'ICE BofA U.S. High Yield Option-Adjusted Spread',
    'BAMLC0A4CBBB': 'ICE BofA BBB Corporate Option-Adjusted Spread',
    'BAMLC0A1AALH': 'ICE BofA AA Corporate Option-Adjusted Spread',
    'AAA': 'Moody\'s Seasoned Aaa Corporate Bond Yield',
    'BAA': 'Moody\'s Seasoned Baa Corporate Bond Yield',
    'DBAA': 'Moody\'s Daily Seasoned Baa Corporate Bond Yield',
    'DAAA': 'Moody\'s Daily Seasoned Aaa Corporate Bond Yield',

    # === VI. MONEY SUPPLY, SYSTEMIC CREDIT & DEBT ===
    'M2SL': 'M2 Money Supply',
    'M1SL': 'M1 Money Supply',
    'M2V': 'Velocity of M2 Money Supply',
    'TOTCI': 'Commercial and Industrial Loans',
    'BUSLOANS': 'Commercial and Industrial Loans (Alternative)',
    'TOTALSL': 'Total Consumer Credit Outstanding',
    'REVOLSL': 'Revolving Consumer Credit Outstanding',
    'NONREVOLSL': 'Nonrevolving Consumer Credit Outstanding',
    'GFDEBTN': 'Federal Debt: Total Public Debt',
    'GFDEGDQ188S': 'Federal Debt Held by the Public as Percent of GDP',
    'REALLN': 'Real Estate Loans: All Commercial Banks',
    'CCLACBW027SBOG': 'Consumer Loans: Credit Cards and Other',
    'TLBSNNCB': 'Nonfinancial Corporate Business; Total Liabilities',
    'TCMDO': 'Total Credit Market Debt Outstanding',
    'FODSP': 'Household Financial Obligations Ratio',

    # === VII. HOUSING, CONSUMER BEHAVIOR & GLOBAL TRADE ===
    'UMCSENT': 'University of Michigan Consumer Sentiment Index',
    'CSUSHPISA': 'S&P CoreLogic Case-Shiller U.S. National Home Price Index',
    'HOUST': 'Housing Starts: Total New Privately Owned Houses',
    'PERMIT': 'New Private Housing Units Authorized',
    'HSN1F': 'New Single-Family Houses Sold',
    'EXHOSLUSM495N': 'Existing Home Sales',
    'MORTGAGE30US': '30-Year Fixed Rate Mortgage Average',
    'BOPGSTB': 'U.S. International Trade in Goods and Services Deficit/Surplus',
    'TWEXBPAE01': 'Real Broad Dollar Index',
    'DTWEXAFEGS': 'Nominal Goods Dollar Index'
}