import yfinance as yf
import pandas as pd
import requests
from datetime import datetime, timedelta
import os

ticker_commodities = {
    # === I. ENERGY & ENVIRONMENTAL MARKETS ===
    'CL=F': 'Crude Oil Futures',
    'BZ=F': 'Brent Crude Oil Futures',
    'NG=F': 'Natural Gas Futures',
    'RB=F': 'RBOB Gasoline Futures',
    'HO=F': 'Heating Oil Futures',
    'G=F': 'Gasoline Futures (Historical/Proxy)',
    'TTF=F': 'Dutch TTF Natural Gas Futures',
    'JKM=F': 'Japan/Korea LNG Futures',
    'MTF=F': 'Methanol Futures',
    'NCF=F': 'Newcastle Coal Futures',
    'ZK=F': 'Ethanol Futures',
    'KRBN': 'KraneShares Global Carbon Strategy ETF',
    'URA': 'Global X Uranium ETF',
    'XLE': 'Energy Select Sector SPDR Fund',
    'UNG': 'United States Natural Gas Fund',
    'USO': 'United States Oil Fund',
    'BNO': 'United States Brent Oil Fund',
    'KMLM': 'KFA Mount Lucas Index Strategy ETF',

    # === II. PRECIOUS METALS ===
    'GC=F': 'Gold Futures',
    'SI=F': 'Silver Futures',
    'PL=F': 'Platinum Futures',
    'PA=F': 'Palladium Futures',
    'GLD': 'SPDR Gold Shares',
    'SLV': 'iShares Silver Trust',
    'PPLT': 'abrdn Physical Platinum Shares ETF',
    'PALL': 'abrdn Physical Palladium Shares ETF',
    'IAU': 'iShares Gold Trust',
    'PSLV': 'Sprott Physical Silver Trust',

    # === III. BASE, INDUSTRIAL & TRANSITION METALS ===
    'HG=F': 'Copper Futures',
    'ALI=F': 'Aluminum Futures',
    'DBB': 'Invesco DB Base Metals Fund',
    'LIT': 'Global X Lithium & Battery Tech ETF',
    'REMX': 'VanEck Rare Earth/Strategic Metals ETF',
    'SLX': 'VanEck Steel ETF',
    'COPX': 'Global X Copper Miners ETF',
    'PICK': 'iShares MSCI Global Metals & Mining Producers ETF',
    'VALE': 'Vale S.A.',
    'RIO': 'Rio Tinto Group',
    'BHP': 'BHP Group Limited',
    'FCX': 'Freeport-McMoRan Inc.',
    'AA': 'Alcoa Corporation',
    'NUE': 'Nucor Corporation',
    'STLD': 'Steel Dynamics, Inc.',
    'XBM.TO': 'iShares S&P/TSX Global Base Metals Index ETF',
    'JJCTF': 'iPath Series B Bloomberg Copper Subindex Total Return ETN',
    'CPER': 'United States Copper Index Fund',
    'GLNCY': 'Glencore plc',
    'ANFGF': 'Anglo American plc',
    'HBM': 'Hudbay Minerals Inc.',
    'TECK': 'Teck Resources Limited',

    # === IV. AGRICULTURAL GRAINS & OILSEEDS ===
    'ZC=F': 'Corn Futures',
    'ZW=F': 'Wheat Futures',
    'ZS=F': 'Soybean Futures',
    'ZM=F': 'Soybean Meal Futures',
    'ZL=F': 'Soybean Oil Futures',
    'ZR=F': 'Rough Rice Futures',
    'ZO=F': 'Oat Futures',
    'KE=F': 'KC Hard Red Winter Wheat Futures',
    'MG=F': 'Spring Wheat Futures',
    'CORN': 'Teucrium Corn Fund',
    'WEAT': 'Teucrium Wheat Fund',
    'SOYB': 'Teucrium Soybean Fund',
    'DBA': 'Invesco DB Agriculture Fund',
    'TAGS': 'Teucrium Agricultural Fund',
    'MOO': 'VanEck Agribusiness ETF',
    'BG': 'Bunge Global SA',
    'ADM': 'Archer-Daniels-Midland Company',
    'ANDE': 'The Andersons, Inc.',
    'NTR': 'Nutrien Ltd.',
    'MOS': 'The Mosaic Company',

    # === V. SOFTS, FIBERS & FOREST PRODUCTS ===
    'KC=F': 'Coffee C Futures',
    'CC=F': 'Cocoa Futures',
    'SB=F': 'Sugar No. 11 Futures',
    'CT=F': 'Cotton No. 2 Futures',
    'OJ=F': 'Orange Juice Futures',
    'LBS=F': 'Lumber Futures',
    'JO': 'iPath Series B Bloomberg Coffee Subindex Total Return ETN',
    'NIB': 'iPath Series B Bloomberg Cocoa Subindex Total Return ETN',
    'SGG': 'iPath Series B Bloomberg Sugar Subindex Total Return ETN',
    'BAL': 'iPath Series B Bloomberg Cotton Subindex Total Return ETN',
    'WOOD': 'iShares Global Timber & Forestry ETF',
    'CUT': 'Invesco MSCI Global Timber ETF',
    'WY': 'Weyerhaeuser Company',
    'PCH': 'PotlatchDeltic Corporation',
    'IP': 'International Paper Company',
    'CTVA': 'Corteva, Inc.',
    'FMC': 'FMC Corporation',
    'SMG': 'The Scotts Miracle-Gro Company',
    'UFS': 'Domtar Corporation',
    'SUZ': 'Suzano S.A.',

    # === VI. LIVESTOCK, POULTRY & DAIRY ===
    'LE=F': 'Live Cattle Futures',
    'GF=F': 'Feeder Cattle Futures',
    'HE=F': 'Lean Hog Futures',
    'DC=F': 'Class III Milk Futures',
    'GNF=F': 'General/Other Livestock Proxy',
    'COW': 'iPath Series B Bloomberg Livestock Subindex Total Return ETN',
    'TSN': 'Tyson Foods, Inc.',
    'PPC': 'Pilgrim\'s Pride Corporation',
    'HRL': 'Hormel Foods Corporation',
    'BRFS': 'BRF S.A.'
}