

ticker_us = {
    'AAPL': 'Apple Inc.', 'MSFT': 'Microsoft Corporation', 'NVDA': 'NVIDIA Corporation', 
    'AMZN': 'Amazon.com, Inc.', 'GOOGL': 'Alphabet Inc. Class A', 'GOOG': 'Alphabet Inc. Class C', 
    'META': 'Meta Platforms, Inc.', 'BRK.B': 'Berkshire Hathaway Inc. Class B', 'LLY': 'Eli Lilly and Company', 
    'AVGO': 'Broadcom Inc.', 'TSLA': 'Tesla, Inc.', 'JPM': 'JPMorgan Chase & Co.', 
    'UNH': 'UnitedHealth Group Incorporated', 'V': 'Visa Inc.', 'XOM': 'Exxon Mobil Corporation', 
    'MA': 'Mastercard Incorporated', 'HD': 'The Home Depot, Inc.', 'PG': 'The Procter & Gamble Company', 
    'COST': 'Costco Wholesale Corporation', 'JNJ': 'Johnson & Johnson', 'AMD': 'Advanced Micro Devices, Inc.', 
    'NFLX': 'Netflix, Inc.', 'ABBV': 'AbbVie Inc.', 'ORCL': 'Oracle Corporation', 
    'CRM': 'Salesforce, Inc.', 'BAC': 'Bank of America Corporation', 'CVX': 'Chevron Corporation', 
    'WMT': 'Walmart Inc.', 'MRK': 'Merck & Co., Inc.', 'WFC': 'Wells Fargo & Company', 
    'DIS': 'The Walt Disney Company', 'PEP': 'PepsiCo, Inc.', 'CSCO': 'Cisco Systems, Inc.', 
    'ADBE': 'Adobe Inc.', 'KO': 'The Coca-Cola Company', 'TMO': 'Thermo Fisher Scientific Inc.', 
    'QCOM': 'QUALCOMM Incorporated', 'ACN': 'Accenture plc', 'GE': 'General Electric Company', 
    'LIN': 'Linde plc', 'MCD': 'McDonald\'s Corporation', 'PM': 'Philip Morris International Inc.', 
    'ABT': 'Abbott Laboratories', 'AXP': 'American Express Company', 'ISRG': 'Intuitive Surgical, Inc.', 
    'IBM': 'International Business Machines Corporation', 'TXN': 'Texas Instruments Incorporated', 
    'MS': 'Morgan Stanley', 'GS': 'The Goldman Sachs Group, Inc.', 'AMGN': 'Amgen Inc.', 
    'HON': 'Honeywell International Inc.', 'CAT': 'Caterpillar Inc.', 'SPGI': 'S&P Global Inc.', 
    'BKNG': 'Booking Holdings Inc.', 'NOW': 'ServiceNow, Inc.', 'PFE': 'Pfizer Inc.', 
    'NKE': 'NIKE, Inc.', 'INTU': 'Intuit Inc.', 'LOW': 'Lowe\'s Companies, Inc.', 
    'COP': 'ConocoPhillips', 'SYK': 'Stryker Corporation', 'C': 'Citigroup Inc.', 
    'LRCX': 'Lam Research Corporation', 'BLK': 'BlackRock, Inc.', 'TJX': 'The TJX Companies, Inc.', 
    'UNP': 'Union Pacific Corporation', 'REGN': 'Regeneron Pharmaceuticals, Inc.', 
    'PLTR': 'Palantir Technologies Inc.', 'MDLZ': 'Mondelez International, Inc.', 
    'BA': 'The Boeing Company', 'VRTX': 'Vertex Pharmaceuticals Incorporated', 
    'ADI': 'Analog Devices, Inc.', 'AXON': 'Axon Enterprise, Inc.', 'UBER': 'Uber Technologies, Inc.', 
    'BX': 'Blackstone Inc.', 'PANW': 'Palo Alto Networks, Inc.', 'DE': 'Deere & Company', 
    'CI': 'The Cigna Group', 'ELV': 'Elevance Health, Inc.', 'CB': 'Chubb Limited', 
    'GILD': 'Gilead Sciences, Inc.', 'MMC': 'Marsh & McLennan Companies, Inc.', 
    'LMT': 'Lockheed Martin Corporation', 'AMAT': 'Applied Materials, Inc.', 
    'MU': 'Micron Technology, Inc.', 'KKR': 'KKR & Co. Inc.', 'MDT': 'Medtronic plc', 
    'ANET': 'Arista Networks, Inc.', 'CRWD': 'CrowdStrike Holdings, Inc.', 
    'KLAC': 'KLA Corporation', 'HCA': 'HCA Healthcare, Inc.', 'FI': 'Fiserv, Inc.', 
    'CDNS': 'Cadence Design Systems, Inc.', 'GEV': 'GE Vernova Inc.', 'ICE': 'Intercontinental Exchange, Inc.', 
    'ETN': 'Eaton Corporation plc', 'MO': 'Altria Group, Inc.', 'WM': 'Waste Management, Inc.', 
    'SHW': 'The Sherwin-Williams Company', 'EOG': 'EOG Resources, Inc.', 'ORLY': 'O\'Reilly Automotive, Inc.', 
    'T': 'AT&T Inc.', 'BSX': 'Boston Scientific Corporation', 'PGR': 'The Progressive Corporation', 
    'CMG': 'Chipotle Mexican Grill, Inc.', 'DUK': 'Duke Energy Corporation', 'PH': 'Parker-Hannifin Corporation', 
    'NOC': 'Northrop Grumman Corporation', 'GD': 'General Dynamics Corporation', 
    'MCK': 'McKesson Corporation', 'MAR': 'Marriott International, Inc.', 
    'SLB': 'SLB (Schlumberger)', 'CTAS': 'Cintas Corporation', 'NXPI': 'NXP Semiconductors N.V.', 
    'CVS': 'CVS Health Corporation', 'MPC': 'Marathon Petroleum Corporation', 
    'TT': 'Trane Technologies plc', 'SNPS': 'Synopsys, Inc.', 'APH': 'Amphenol Corporation', 
    'ECL': 'Ecolab Inc.', 'ITW': 'Illinois Tool Works Inc.', 'EMR': 'Emerson Electric Co.', 
    'COR': 'Cencora, Inc.', 'HUM': 'Humana Inc.', 'ADSK': 'Autodesk, Inc.', 
    'AON': 'Aon plc', 'MCO': 'Moody\'s Corporation', 'ROST': 'Ross Stores, Inc.', 
    'PCAR': 'PACCAR Inc.', 'HLT': 'Hilton Worldwide Holdings Inc.', 'AIG': 'American International Group, Inc.', 
    'BKR': 'Baker Hughes Company', 'AEP': 'American Electric Power Company, Inc.', 
    'WELL': 'Welltower Inc.', 'PAYX': 'Paychex, Inc.', 'DHR': 'Danaher Corporation', 
    'CARR': 'Carrier Global Corporation', 'FIS': 'Fidelity National Information Services, Inc.', 
    'TEL': 'TE Connectivity Ltd.', 'O': 'Realty Income Corporation', 'D': 'Dominion Energy, Inc.', 
    'KMB': 'Kimberly-Clark Corporation', 'MNST': 'Monster Beverage Corporation', 
    'TRV': 'The Travelers Companies, Inc.', 'OKE': 'ONEOK, Inc.', 'CMI': 'Cummins Inc.', 
    'AZO': 'AutoZone, Inc.', 'FDX': 'FedEx Corporation', 'SPG': 'Simon Property Group, Inc.', 
    'CPRT': 'Copart, Inc.', 'AJG': 'Arthur J. Gallagher & Co.', 'SBUX': 'Starbucks Corporation', 
    'MET': 'MetLife, Inc.', 'GIS': 'General Mills, Inc.', 'HAL': 'Halliburton Company', 
    'LEN': 'Lennar Corporation', 'ALL': 'The Allstate Corporation', 'OXY': 'Occidental Petroleum Corporation', 
    'GWW': 'W.W. Grainger, Inc.', 'NSC': 'Norfolk Southern Corporation', 'PSA': 'Public Storage', 
    'DLR': 'Digital Realty Trust, Inc.', 'KDP': 'Keurig Dr Pepper Inc.', 'VRSK': 'Verisk Analytics, Inc.', 
    'ED': 'Consolidated Edison, Inc.', 'ODFL': 'Old Dominion Freight Line, Inc.', 
    'HWM': 'Howmet Aerospace Inc.', 'FAST': 'Fastenal Company', 'PRU': 'Prudential Financial, Inc.', 
    'CTVA': 'Corteva, Inc.', 'YUM': 'Yum! Brands, Inc.', 'EXC': 'Exelon Corporation', 
    'STZ': 'Constellation Brands, Inc.', 'AFL': 'Aflac Incorporated', 'WMB': 'The Williams Companies, Inc.', 
    'VICI': 'VICI Properties Inc.', 'XEL': 'Xcel Energy Inc.', 'KR': 'The Kroger Co.', 
    'IDXX': 'IDEXX Laboratories, Inc.', 'CEG': 'Constellation Energy Corporation', 
    'URI': 'United Rentals, Inc.', 'ROK': 'Rockwell Automation, Inc.', 'CSX': 'CSX Corporation', 
    'HPQ': 'HP Inc.', 'EA': 'Electronic Arts Inc.', 'LUV': 'Southwest Airlines Co.', 
    'CNC': 'Centene Corporation', 'MTD': 'Mettler-Toledo International Inc.', 
    'EFX': 'Equifax Inc.', 'KMI': 'Kinder Morgan, Inc.', 'DAL': 'Delta Air Lines, Inc.', 
    'PEG': 'Public Service Enterprise Group Incorporated', 'RMD': 'ResMed Inc.', 
    'VLO': 'Valero Energy Corporation', 'CTSH': 'Cognizant Technology Solutions Corporation', 
    'WTW': 'Willis Towers Watson Public Limited Company', 'KEYS': 'Keysight Technologies, Inc.', 
    'FITB': 'Fifth Third Bancorp', 'STT': 'State Street Corporation', 'FTV': 'Fortive Corporation', 
    'PPG': 'PPG Industries, Inc.', 'SYY': 'Sysco Corporation', 'EQIX': 'Equinix, Inc.', 
    'EIX': 'Edison International', 'CDW': 'CDW Corporation', 'CBRE': 'CBRE Group, Inc.', 
    'TFC': 'Truist Financial Corporation', 'GLW': 'Corning Incorporated', 'ADM': 'Archer-Daniels-Midland Company', 
    'WST': 'West Pharmaceutical Services, Inc.', 'CAH': 'Cardinal Health, Inc.', 
    'DLTR': 'Dollar Tree, Inc.', 'FMC': 'FMC Corporation', 'VMC': 'Vulcan Materials Company', 
    'BBY': 'Best Buy Co., Inc.', 'BALL': 'Ball Corporation', 'NVR': 'NVR, Inc.', 
    'HUBB': 'Hubbell Incorporated', 'DOV': 'Dover Corporation', 'HIG': 'The Hartford Financial Services Group, Inc.', 
    'BRO': 'Brown & Brown, Inc.', 'IRM': 'Iron Mountain Incorporated', 'STX': 'Seagate Technology Holdings plc', 
    'NDAQ': 'Nasdaq, Inc.', 'SRE': 'Sempra', 'WEC': 'WEC Energy Group, Inc.', 
    'SBAC': 'SBA Communications Corporation', 'NTRS': 'Northern Trust Corporation', 
    'ALGN': 'Align Technology, Inc.', 'TYL': 'Tyler Technologies, Inc.', 'AWK': 'American Water Works Company, Inc.', 
    'WDC': 'Western Digital Corporation', 'GDDY': 'GoDaddy Inc.', 'WBD': 'Warner Bros. Discovery, Inc.', 
    'NTAP': 'NetApp, Inc.', 'BXP': 'BXP, Inc.', 'HES': 'Hess Corporation', 'CL': 'Colgate-Palmolive Company', 
    'ALB': 'Albemarle Corporation', 'A': 'Agilent Technologies, Inc.', 'DPZ': 'Domino\'s Pizza, Inc.', 
    'TROW': 'T. Rowe Price Group, Inc.', 'IEX': 'IDEX Corporation', 'ES': 'Eversource Energy', 
    'FE': 'FirstEnergy Corp.', 'DRI': 'Darden Restaurants, Inc.', 'SWKS': 'Skyworks Solutions, Inc.', 
    'DTE': 'DTE Energy Company', 'JBHT': 'J.B. Hunt Transport Services, Inc.', 
    'TSCO': 'Tractor Supply Company', 'ARE': 'Alexandria Real Estate Equities, Inc.', 
    'BG': 'Bunge Global SA', 'AOS': 'A. O. Smith Corporation', 'INVH': 'Invitation Homes Inc.', 
    'WY': 'Weyerhaeuser Company', 'AVY': 'Avery Dennison Corporation', 'APA': 'APA Corporation', 
    'RF': 'Regions Financial Corporation', 'HBAN': 'Huntington Bancshares Incorporated', 
    'EXR': 'Extra Space Storage Inc.', 'COO': 'The Cooper Companies, Inc.', 
    'EQR': 'Equity Residential', 'VTR': 'Ventas, Inc.', 'AKAM': 'Akamai Technologies, Inc.', 
    'IFF': 'International Flavors & Fragrances Inc.', 'MGM': 'MGM Resorts International', 
    'ZBRA': 'Zebra Technologies Corporation', 'HAS': 'Hasbro, Inc.', 'SNA': 'Snap-on Incorporated', 
    'OMC': 'Omnicom Group Inc.', 'K': 'Kellanova', 'RE': 'Everest Group, Ltd.', 
    'SWK': 'Stanley Black & Decker, Inc.', 'XYL': 'Xylem Inc.', 'CHRW': 'C.H. Robinson Worldwide, Inc.', 
    'IP': 'International Paper Company', 'LKQ': 'LKQ Corporation', 'TAP': 'Molson Coors Beverage Company', 
    'LNT': 'Alliant Energy Corporation', 'AIZ': 'Assurant, Inc.', 'CPB': 'Campbell Soup Company', 
    'JNPR': 'Juniper Networks, Inc.', 'TPR': 'Tapestry, Inc.', 'ALLE': 'Allegion plc', 
    'ZION': 'Zions Bancorporation, N.A.', 'PNR': 'Pentair plc', 'XRAY': 'Dentsply Sirona Inc.', 
    'NWL': 'Newell Brands Inc.', 'FRT': 'Federal Realty Investment Trust', 
    'CMA': 'Comerica Incorporated', 'HRL': 'Hormel Foods Corporation', 'MHK': 'Mohawk Industries, Inc.', 
    'AAL': 'American Airlines Group Inc.', 'SEE': 'Sealed Air Corporation', 
    'NWSA': 'News Corporation Class A', 'NWS': 'News Corporation Class B', 
    'FOXA': 'Fox Corporation Class A', 'FOX': 'Fox Corporation Class B', 
    'DELL': 'Dell Technologies Inc.', 'VST': 'Vistra Corp.', 'CE': 'Celanese Corporation', 
    'MCHP': 'Microchip Technology Incorporated', 'TER': 'Teradyne, Inc.', 
    'QRVO': 'Qorvo, Inc.', 'MPWR': 'Monolithic Power Systems, Inc.', 'FSLR': 'First Solar, Inc.', 
    'ENPH': 'Enphase Energy, Inc.', 'ON': 'ON Semiconductor Corporation', 
    'KVUE': 'Kenvue Inc.', 'GEHC': 'GE HealthCare Technologies Inc.', 
    'SMCI': 'Super Micro Computer, Inc.', 'HPE': 'Hewlett Packard Enterprise Company', 
    'PSTG': 'Pure Storage, Inc.', 'SOFI': 'SoFi Technologies, Inc.', 'APO': 'Apollo Global Management, Inc.', 
    'BEN': 'Franklin Resources, Inc.', 'IVZ': 'Invesco Ltd.', 'AMP': 'Ameriprise Financial, Inc.', 
    'COF': 'Capital One Financial Corporation', 'DFS': 'Discover Financial Services', 
    'AMCR': 'Amcor plc', 'AEE': 'Ameren Corporation', 'ATO': 'Atmos Energy Corporation', 
    'AVB': 'AvalonBay Communities, Inc.', 'BAX': 'Baxter International Inc.', 
    'BDX': 'Becton, Dickinson and Company', 'BF.B': 'Brown-Forman Corporation Class B', 
    'BIIB': 'Biogen Inc.', 'BIO': 'Bio-Rad Laboratories, Inc.', 'BK': 'The Bank of New York Mellon Corporation', 
    'BMY': 'Bristol-Myers Squibb Company', 'BR': 'Broadridge Financial Solutions, Inc.', 
    'CAG': 'Conagra Brands, Inc.', 'CCI': 'Crown Castle Inc.', 'CCL': 'Carnival Corporation & plc', 
    'CF': 'CF Industries Holdings, Inc.', 'CFG': 'Citizens Financial Group, Inc.', 
    'CHD': 'Church & Dwight Co., Inc.', 'CINF': 'Cincinnati Financial Corporation', 
    'CLX': 'The Clorox Company', 'CME': 'CME Group Inc.', 'CMS': 'CMS Energy Corporation', 
    'CNP': 'CenterPoint Energy, Inc.', 'CPT': 'Camden Property Trust', 'CRL': 'Charles River Laboratories International, Inc.', 
    'CSGP': 'CoStar Group, Inc.', 'CTRA': 'Coterra Energy Inc.', 'CZR': 'Caesars Entertainment, Inc.', 
    'DAY': 'RPM International Inc.', 'DD': 'DuPont de Nemours, Inc.', 'DG': 'Dollar General Corporation', 
    'DGX': 'Quest Diagnostics Incorporated', 'DHI': 'D.R. Horton, Inc.', 'DISH': 'DISH Network Corporation', 
    'DOW': 'Dow Inc.', 'DVA': 'DaVita Inc.', 'DVN': 'Devon Energy Corporation', 
    'DXCM': 'DexCom, Inc.', 'DXC': 'DXC Technology Company', 'EG': 'Everest Group, Ltd.', 
    'EL': 'The Estée Lauder Companies Inc.', 'EMN': 'Eastman Chemical Company', 
    'ESS': 'Essex Property Trust, Inc.', 'ETR': 'Entergy Corporation', 'ETY': 'Eaton Vance Tax-Managed Buy-Write Opportunities Fund', 
    'EVRG': 'Evergy, Inc.', 'EW': 'Edwards Lifesciences Corporation', 'EXPD': 'Expeditors International of Washington, Inc.', 
    'EXPE': 'Expedia Group, Inc.', 'FANG': 'Diamondback Energy, Inc.', 'FICO': 'Fair Isaac Corporation', 
    'GEN': 'Gen Digital Inc.', 'GL': 'Globe Life Inc.', 'GNRC': 'Generac Holdings Inc.', 
    'GPC': 'Genuine Parts Company', 'GPN': 'Global Payments Inc.', 'GRMN': 'Garmin Ltd.', 
    'HII': 'Huntington Ingalls Industries, Inc.', 'HOLX': 'Hologic, Inc.', 
    'HSIC': 'Henry Schein, Inc.', 'HST': 'Host Hotels & Resorts, Inc.', 'HSY': 'The Hershey Company', 
    'ILMN': 'Illumina, Inc.', 'INCY': 'Incyte Corporation', 'IPG': 'The Interpublic Group of Companies, Inc.', 
    'IQV': 'IQVIA Holdings Inc.', 'IR': 'Ingersoll Rand Inc.', 'IT': 'Gartner, Inc.', 
    'J': 'Jacobs Solutions Inc.', 'JBL': 'Jabil Inc.', 'JCI': 'Johnson Controls International plc', 
    'JKHY': 'Jack Henry & Associates, Inc.', 'KIM': 'Kimco Realty Corporation', 
    'KMX': 'CarMax, Inc.', 'L': 'Loews Corporation', 'LDOS': 'Leidos Holdings, Inc.', 
    'LH': 'Laboratory Corporation of America Holdings', 'LHX': 'L3Harris Technologies, Inc.', 
    'LII': 'Lennox International Inc.', 'LULU': 'Lululemon Athletica Inc.', 
    'MKC': 'McCormick & Company, Incorporated', 'MKTX': 'MarketAxess Holdings Inc.', 
    'MLM': 'Martin Marietta Materials, Inc.', 'MRNA': 'Moderna, Inc.', 'MSI': 'Motorola Solutions, Inc.', 
    'MTB': 'M&T Bank Corporation', 'NEM': 'Newmont Corporation', 'NRG': 'NRG Energy, Inc.', 
    'NUE': 'Nucor Corporation', 'PARA': 'Paramount Global', 'PAYC': 'Paycom Software, Inc.', 
    'PCTY': 'Paylocity Holding Corporation', 'PENN': 'PENN Entertainment, Inc.', 
    'PFG': 'Principal Financial Group, Inc.', 'PNW': 'Pinnacle West Capital Corporation', 
    'POOL': 'Pool Corporation', 'PTC': 'PTC Inc.', 'PWR': 'Quanta Services, Inc.', 
    'RHI': 'Robert Half Inc.', 'RL': 'Ralph Lauren Corporation', 'RNG': 'RingCentral, Inc.', 
    'SJM': 'The J. M. Smucker Company', 'SNOW': 'Snowflake Inc.', 'SOLV': 'Solventum Corporation', 
    'SQ': 'Block, Inc.', 'SRCL': 'Stericycle, Inc.', 'SSNC': 'SS&C Technologies Holdings, Inc.', 
    'SUM': 'Summit Materials, Inc.', 'SYF': 'Synchrony Financial', 'TECH': 'Bio-Techne Corporation', 
    'TENB': 'Tenable Holdings, Inc.', 'TEX': 'Terex Corporation', 'TFX': 'Teleflex Incorporated', 
    'TGNA': 'TEGNA Inc.', 'TGT': 'Target Corporation', 'THC': 'Tenet Healthcare Corporation', 
    'TKR': 'Timken Company', 'TMUS': 'T-Mobile US, Inc.', 'TPX': 'Tempur Sealy International, Inc.', 
    'TRMB': 'Trimble Inc.', 'TTC': 'The Toro Company', 'TXG': '10x Genomics, Inc.', 
    'UA': 'Under Armour, Inc. Class C', 'UAA': 'Under Armour, Inc. Class A', 
    'UAL': 'United Airlines Holdings, Inc.', 'UDR': 'UDR, Inc.', 'UHS': 'Universal Health Services, Inc.', 
    'ULTA': 'Ulta Beauty, Inc.', 'VFC': 'V.F. Corporation', 'VNO': 'Vornado Realty Trust', 
    'VNT': 'Vontier Corporation', 'VRSN': 'VeriSign, Inc.', 'VTRS': 'Viatris Inc.', 
    'WAB': 'Westinghouse Air Brake Technologies Corporation', 'WAT': 'Waters Corporation', 
    'WBA': 'Walgreens Boots Alliance, Inc.', 'WHR': 'Whirlpool Corporation'
}

ticker_de = {
    'SAP.DE': 'SAP SE',
    'SIE.DE': 'Siemens AG',
    'ALV.DE': 'Allianz SE',
    'DTE.DE': 'Deutsche Telekom AG',
    'ENR.DE': 'Siemens Energy AG',
    'IFX.DE': 'Infineon Technologies AG',
    'RHM.DE': 'Rheinmetall AG',
    'DHL.DE': 'DHL Group',
    'MRK.DE': 'Merck KGaA',
    'MUV2.DE': 'Münchener Rückversicherungs-Gesellschaft AG',
    'DBK.DE': 'Deutsche Bank AG',
    'MBG.DE': 'Mercedes-Benz Group AG',
    'VOW3.DE': 'Volkswagen AG',
    'EOAN.DE': 'E.ON SE',
    'BMW.DE': 'Bayerische Motoren Werke AG',
    'BAS.DE': 'BASF SE',
    'DB1.DE': 'Deutsche Börse AG',
    'P911.DE': 'Dr. Ing. h.c. F. Porsche AG',
    'RWE.DE': 'RWE AG',
    'SHL.DE': 'Siemens Healthineers AG',
    'CBK.DE': 'Commerzbank AG',
    'HEI.DE': 'Heidelberg Materials AG',
    'DTG.DE': 'Daimler Truck Holding AG',
    'ADS.DE': 'Adidas AG',
    'FRE.DE': 'Fresenius SE & Co. KGaA',
    'VNA.DE': 'Vonovia SE',
    'BEI.DE': 'Beiersdorf AG',
    'CON.DE': 'Continental AG',
    'SY1.DE': 'Symrise AG',
    'QIA.DE': 'Qiagen N.V.',
    'HNR1.DE': 'Hannover Rück SE',
    'MTX.DE': 'MTU Aero Engines AG',
    'HEN3.DE': 'Henkel AG & Co. KGaA',
    'SRT3.DE': 'Sartorius AG',
    'ZAL.DE': 'Zalando SE',
    'FME.DE': 'Fresenius Medical Care AG & Co. KGaA',
    'G24.DE': 'GRENKE AG',
    'PUM.DE': 'PUMA SE',
    'EVK.DE': 'Evonik Industries AG',
    'WCH.DE': 'Wacker Chemie AG',
    'LEG.DE': 'LEG Immobilien SE',
    'KBX.DE': 'Knorr-Bremse AG',
    'HOT.DE': 'Hochtief AG',
    'AIXA.DE': 'Aixtron SE',
    'AM3D.DE': 'Amadeus Fire AG',
    'NDX1.DE': 'Nordex SE',
    'AFX.DE': 'Carl Zeiss Meditec AG',
    'HFG.DE': 'HelloFresh SE',
    'BOSS.DE': 'HUGO BOSS AG',
    'FRA.DE': 'Fraport AG',
    'EVD.DE': 'Evotec SE',
    'TUI1.DE': 'TUI AG',
    'LHA.DE': 'Deutsche Lufthansa AG',
    'JUN3.DE': 'Jungheinrich AG',
    'G1A.DE': 'GEA Group AG',
    'SDF.DE': 'K+S AG',
    'TAG.DE': 'TAG Immobilien AG',
    'SGL.DE': 'SGL Carbon SE',
    'BC8.DE': 'Aroundtown SA',
    'HAG.DE': 'Hamburger Hafen und Logistik AG',
    'GYC.DE': 'GFT Technologies SE',
    'FPE3.DE': 'Ferratum Oyj (Multitude SE)',
    'SMHN.DE': 'SMT Scharf AG',
    'NDA.DE': 'Aurubis AG',
    'GLJ.DE': 'Global Fashion Group S.A.',
    'PNE3.DE': 'PNE AG',
    'O2D.DE': 'Telefónica Deutschland Holding AG',
    'NEM.DE': 'Nemetschek SE',
    'GFT.DE': 'GFT Technologies SE',
    'HDD.DE': 'Hamburger Hafen und Logistik AG',
    'DUE.DE': 'Dürr AG',
    'CEC.DE': 'Ceconomy AG',
    'ARL.DE': 'Aareal Bank AG',
    'B4B.DE': 'Borussia Dortmund GmbH & Co. KGaA',
    '1U1.DE': '1&1 AG',
    'RAA.DE': 'Rational AG',
    'HYQ.DE': 'Hypoport SE',
    'DWNI.DE': 'Deutsche Wohnen SE',
    'DHER.DE': 'Delivery Hero SE',
    'EVT.DE': 'Evotec SE',
    'BVB.DE': 'Borussia Dortmund GmbH & Co. KGaA',
    'SOW.DE': 'Software AG',
    'PFV.DE': 'Pfeiffer Vacuum Technology AG',
    'WAF.DE': 'Siltronic AG',
    'SAX.DE': 'Stada Arzneimittel AG',
    'VTSC.DE': 'Vitesco Technologies Group AG',
    'TLX.DE': 'Talanx AG',
    'EUZ.DE': 'Euromicron AG',
    'GXI.DE': 'Gerresheimer AG',
    'AOX.DE': 'Alstria Office REIT-AG',
    'COK.DE': 'CompuGroup Medical SE & Co. KGaA',
    'GMM.DE': 'Grammer AG',
    'SANT.DE': 'Santa Fe Group A/S',
    'ADV.DE': 'Adva Optical Networking SE',
    'UTDI.DE': 'United Internet AG',
    'SXT.DE': 'Sensirion Holding AG',
    'MLP.DE': 'MLP SE',
    'KRN.DE': 'Krones AG',
    'IVU.DE': 'IVU Traffic Technologies AG',
    'ZIL2.DE': 'Zalando SE',
    'BYW6.DE': 'BayWa AG',
    'BWB.DE': 'BWT Aktiengesellschaft',
    'ECV.DE': 'Eckert & Ziegler AG',
    'AAQ.DE': 'aamadoo AG',
    'TTR1.DE': 'TeamViewer SE',
    'D6H.DE': 'Deutsche Beteiligungs AG',
    'VBK.DE': 'Volksbank AG',
    'STO3.DE': 'Stöbich AG',
    'FORG.DE': 'Forterra plc',
    'PN3.DE': 'PNE AG',
    'PBB.DE': 'Deutsche Pfandbriefbank AG',
    'HBH.DE': 'H&R AG',
    'ELG.DE': 'Elmos Semiconductor SE',
    'WAS.DE': 'WashTec AG',
    'PFT.DE': 'Pfandbriefbank AG',
    'MSLL.DE': 'Maschinenfabrik Berthold Hermle AG',
    'CBB.DE': 'Cewe Stiftung & Co. KGaA',
    'GLA.DE': 'GFT Technologies SE',
    'CWC.DE': 'Cancom SE',
    'MUM.DE': 'Muehlhan AG',
    'FIE.DE': 'Fielmann AG',
    'B5A.DE': 'BayWa AG',
    'BSL.DE': 'Basler AG',
    'ACT.DE': 'Actinium Pharmaceuticals, Inc.',
    'GEC.DE': 'Gerresheimer AG',
    'SYZ.DE': 'SYZYGY AG',
    'BCP.DE': 'Bayer CropScience AG',
    'VTW.DE': 'Vitasun AG',
    'M7U.DE': 'M7 Real Estate',
    'SMT.DE': 'SMT Scharf AG',
    'KCO.DE': 'Klöckner & Co SE',
    'BOS.DE': 'Bossard Holding AG',
    'VIB.DE': 'VIB Vermögen AG',
    'DRE.DE': 'Drägerwerk AG & Co. KGaA',
    'NXG.DE': 'Nexus AG',
    'O1BC.DE': '1&1 AG',
    'KWS.DE': 'KWS Saat SE & Co. KGaA',
    'LHS.DE': 'LHS Telekommunikation',
    'AAD.DE': 'Adva Optical Networking SE',
    'OHB.DE': 'OHB SE',
    'MFT.DE': 'Manz AG',
    'VT9.DE': 'Varta AG',
    'HLE.DE': 'Heidelberger Druckmaschinen AG',
    'SKB.DE': 'Südzucker AG',
    'CAP.DE': 'Caparol AG',
    'SLT.DE': 'Siltronic AG',
    'TNH.DE': 'TUI AG',
    'HHK.DE': 'H&R AG',
    'CLK.DE': 'Carl Zeiss Meditec AG',
    'VAB.DE': 'Varta AG',
    'INH.DE': 'Innate Pharma SA',
    'IFA.DE': 'IFA Hotel & Touristik AG',
    'BYW.DE': 'BayWa AG',
    'SHF.DE': 'Shiftex AG',
    'DBAN.DE': 'Deutsche Bahn AG',
    'NWRK.DE': 'Network AG',
    'MDO.DE': 'Medion AG',
    'PVE.DE': 'PNE AG',
    'IIG.DE': 'IIG AG',
    'SNG.DE': 'SGL Carbon SE',
    'AR4.DE': 'Aroundtown SA',
    'SQU.DE': 'Squer AG',
    'EXX.DE': 'iShares STOXX Europe 600',
    'YOC.DE': 'YOC AG',
    'F3C.DE': 'FCR Immobilien AG',
    'HM7.DE': 'Heidelberg Materials AG',
    'MUX.DE': 'Muehlhan AG',
    'E2N.DE': 'E2N AG',
    'KMT.DE': 'Klöckner & Co SE',
    'KBC.DE': 'KBC Group NV',
    'TTK.DE': 'TUI AG',
    'ED4.DE': 'E.ON SE',
    'AOF.DE': 'AOF AG',
    'BFSA.DE': 'Bayer AG',
    'BEZ.DE': 'Beiersdorf AG',
    'BIJ.DE': 'Bijou Brigitte AG',
    'GBF.DE': 'Gerresheimer AG',
    'EXSG.DE': 'iShares MSCI Europe ESG',
    'EXSA.DE': 'iShares STOXX Europe 600',
    'ISPA.DE': 'iShares MSCI Europe',
    'EXSD.DE': 'iShares STOXX Europe 600',
    'EXSH.DE': 'iShares STOXX Europe 600',
    'EXSE.DE': 'iShares STOXX Europe 600',
    'EXXU.DE': 'iShares STOXX Europe 600',
    'EXX5.DE': 'iShares STOXX Europe 600',
    'EXXT.DE': 'iShares STOXX Europe 600',
    '1NN.DE': '1&1 AG',
    '1SXP.DE': 'iShares STOXX Europe 600',
    '2GB.DE': '2G Energy AG',
    '2HRA.DE': '2HRA AG',
    '3ITN.DE': '3ITN AG',
    '3SQ1.DE': '3SQ1 AG',
    '4DSD.DE': '4DSD AG',
    '4X0.DE': '4X0 AG',
    '7V0.DE': '7V0 AG',
    '93M1.DE': '93M1 AG',
    'A1OS.DE': 'A1OS AG',
    'A6T.DE': 'A6T AG',
    'A7AH.DE': 'A7AH AG',
    'ACX.DE': 'ACX AG'
}

ticker_asia = {
    # --- JAPAN (Tokyo Stock Exchange: .T) ---
    '7203.T': 'Toyota Motor Corporation',
    '8306.T': 'Mitsubishi UFJ Financial Group, Inc.',
    '6758.T': 'Sony Group Corporation',
    '6861.T': 'Keyence Corporation',
    '9983.T': 'Fast Retailing Co., Ltd.',
    '9984.T': 'SoftBank Group Corp.',
    '8035.T': 'Tokyo Electron Limited',
    '7974.T': 'Nintendo Co., Ltd.',
    '4502.T': 'Takeda Pharmaceutical Company Limited',
    '6501.T': 'Hitachi, Ltd.',
    '8001.T': 'Itochu Corporation',
    '8031.T': 'Mitsui & Co., Ltd.',
    '8058.T': 'Mitsubishi Corporation',
    '8411.T': 'Mizuho Financial Group, Inc.',
    '9432.T': 'Nippon Telegraph and Telephone Corporation',
    '9433.T': 'KDDI Corporation',
    '9434.T': 'SoftBank Corp.',
    '6098.T': 'Recruit Holdings Co., Ltd.',
    '4063.T': 'Shin-Etsu Chemical Co., Ltd.',
    '4519.T': 'Chugai Pharmaceutical Co., Ltd.',
    '6902.T': 'Denso Corporation',
    '6920.T': 'Lasertec Corporation',
    '7741.T': 'Hoya Corporation',
    '8316.T': 'Sumitomo Mitsui Financial Group, Inc.',
    '8766.T': 'Tokio Marine Holdings, Inc.',
    '2914.T': 'Japan Tobacco Inc.',
    '3382.T': 'Seven & i Holdings Co., Ltd.',
    '4503.T': 'Astellas Pharma Inc.',
    '4901.T': 'Fujifilm Holdings Corporation',
    '6367.T': 'Daikin Industries, Ltd.',
    '6503.T': 'Mitsubishi Electric Corporation',
    '6702.T': 'Fujitsu Limited',
    '6954.T': 'Fanuc Corporation',
    '6971.T': 'Kyocera Corporation',
    '6981.T': 'Murata Manufacturing Co., Ltd.',
    '7267.T': 'Honda Motor Co., Ltd.',
    '7309.T': 'Shimano Inc.',
    '8053.T': 'Sumitomo Corporation',
    '8113.T': 'Unicharm Corporation',
    '8267.T': 'Aeon Co., Ltd.',
    '8604.T': 'Nomura Holdings, Inc.',
    '8801.T': 'Mitsui Fudosan Co., Ltd.',
    '8802.T': 'Mitsubishi Estate Company, Limited',
    '9020.T': 'East Japan Railway Company',
    '9022.T': 'Central Japan Railway Company',
    '9101.T': 'Nippon Yusen Kabushiki Kaisha',
    '9202.T': 'ANA Holdings Inc.',
    '9613.T': 'NTT Data Group Corporation',
    '9735.T': 'Secom Co., Ltd.',
    '9843.T': 'Nitori Holdings Co., Ltd.',
    '1925.T': 'Daiwa House Industry Co., Ltd.',
    '1928.T': 'Sekisui House, Ltd.',
    '2502.T': 'Asahi Group Holdings, Ltd.',
    '2503.T': 'Kirin Holdings Company, Limited',
    '2802.T': 'Ajinomoto Co., Inc.',
    '3407.T': 'Asahi Kasei Corporation',
    '4188.T': 'Mitsubishi Chemical Group Corporation',
    '4452.T': 'Kao Corporation',
    '4523.T': 'Eisai Co., Ltd.',
    '4528.T': 'Ono Pharmaceutical Co., Ltd.',
    '4568.T': 'Daiichi Sankyo Company, Limited',
    '4578.T': 'Ootsuka Holdings Co., Ltd.',
    '4661.T': 'Oriental Land Co., Ltd.',
    '4911.T': 'Shiseido Company, Limited',
    '5020.T': 'ENEOS Holdings, Inc.',
    '5108.T': 'Bridgestone Corporation',
    '5401.T': 'Nippon Steel Corporation',
    '5713.T': 'Sumitomo Metal Mining Co., Ltd.',
    '6178.T': 'Japan Post Holdings Co., Ltd.',
    '6273.T': 'SMC Corporation',
    '6301.T': 'Komatsu Ltd.',
    '6326.T': 'Kubota Corporation',
    '6504.T': 'Fuji Electric Co., Ltd.',
    '6506.T': 'Yaskawa Electric Corporation',
    '6645.T': 'Omron Corporation',
    '6723.T': 'Renesas Electronics Corporation',
    '6752.T': 'Panasonic Holdings Corporation',
    '6762.T': 'TDK Corporation',
    '6857.T': 'Advantest Corporation',
    '7011.T': 'Mitsubishi Heavy Industries, Ltd.',
    '7201.T': 'Nissan Motor Co., Ltd.',
    '7261.T': 'Mazda Motor Corporation',
    '7269.T': 'Suzuki Motor Corporation',
    '7270.T': 'Subaru Corporation',
    '7733.T': 'Olympus Corporation',
    '7751.T': 'Canon Inc.',
    '7832.T': 'Bandai Namco Holdings Inc.',
    '7951.T': 'Yamaha Corporation',
    '8015.T': 'Toyota Tsusho Corporation',
    '8253.T': 'Credit Saison Co., Ltd.',
    '8308.T': 'Resona Holdings, Inc.',
    '8309.T': 'Sumitomo Miitsui Trust Holdings, Inc.',
    '8331.T': 'The Chiba Bank, Ltd.',
    '8354.T': 'Fukuoka Financial Group, Inc.',
    '8410.T': 'Seven Bank, Ltd.',
    '8591.T': 'Orix Corporation',
    '8593.T': 'Mitsubishi HC Capital Inc.',
    '8630.T': 'Sompo Holdings, Inc.',
    '8725.T': 'MS&AD Insurance Group Holdings, Inc.',
    '8750.T': 'Dai-ichi Life Holdings, Inc.',
    '8795.T': 'T&D Holdings, Inc.',
    '8830.T': 'Sumitomo Realty & Development Co., Ltd.',
    '9005.T': 'Tokyu Corporation',
    '9007.T': 'Odakyu Electric Railway Co., Ltd.',
    '9008.T': 'Keio Corporation',
    '9009.T': 'Keisei Electric Railway Co., Ltd.',
    '9021.T': 'West Japan Railway Company',
    '9041.T': 'Kintetsu Group Holdings Co., Ltd.',
    '9042.T': 'Hankyu Hanshin Holdings, Inc.',
    '9064.T': 'Yamato Holdings Co., Ltd.',
    '9104.T': 'Mitsui O.S.K. Lines, Ltd.',
    '9107.T': 'Kawasaki Kisen Kaisha, Ltd.',
    '9501.T': 'Tokyo Electric Power Company Holdings, Incorporated',
    '9502.T': 'Chubu Electric Power Company, Incorporated',
    '9503.T': 'The Kansai Electric Power Company, Incorporated',
    '9531.T': 'Tokyo Gas Co., Ltd.',
    '9532.T': 'Osaka Gas Co., Ltd.',
    '9602.T': 'Toho Co., Ltd.',
    '9766.T': 'Konami Group Corporation',
    '9982.T': 'Takihyo Co., Ltd.',

    # --- HONG KONG & CHINA OFFSHORE (Hong Kong Stock Exchange: .HK) ---
    '0700.HK': 'Tencent Holdings Limited',
    '9988.HK': 'Alibaba Group Holding Limited',
    '3690.HK': 'Meituan',
    '0939.HK': 'China Construction Bank Corporation',
    '1398.HK': 'Industrial and Commercial Bank of China Limited',
    '1211.HK': 'BYD Company Limited',
    '0857.HK': 'PetroChina Company Limited',
    '3988.HK': 'Bank of China Limited',
    '2318.HK': 'Ping An Insurance (Group) Company of China, Ltd.',
    '0388.HK': 'Hong Kong Exchanges and Clearing Limited',
    '0883.HK': 'CNOOC Limited',
    '0941.HK': 'China Mobile Limited',
    '1088.HK': 'China Shenhua Energy Company Limited',
    '1658.HK': 'Postal Savings Bank of China Co., Ltd.',
    '1810.HK': 'Xiaomi Corporation',
    '2015.HK': 'Li Auto Inc.',
    '2331.HK': 'Li Ning Company Limited',
    '2628.HK': 'China Life Insurance Company Limited',
    '3968.HK': 'China Merchants Bank Co., Ltd.',
    '0001.HK': 'CK Hutchison Holdings Limited',
    '0002.HK': 'CLP Holdings Limited',
    '0003.HK': 'The Hong Kong and China Gas Company Limited',
    '0005.HK': 'HSBC Holdings plc',
    '0006.HK': 'Power Assets Holdings Limited',
    '0011.HK': 'Hang Seng Bank Limited',
    '0012.HK': 'Henderson Land Development Company Limited',
    '0016.HK': 'Sun Hung Kai Properties Limited',
    '0017.HK': 'New World Development Company Limited',
    '0027.HK': 'Galaxy Entertainment Group Limited',
    '0066.HK': 'MTR Corporation Limited',
    '0083.HK': 'Sino Land Company Limited',
    '0101.HK': 'Hang Lung Properties Limited',
    '0151.HK': 'Want Want China Holdings Limited',
    '0175.HK': 'Geely Automobile Holdings Limited',
    '0267.HK': 'CITIC Limited',
    '0288.HK': 'WH Group Limited',
    '0291.HK': 'China Resources Beer (Holdings) Company Limited',
    '0322.HK': 'Tingyi (Cayman Islands) Holding Corp.',
    '0669.HK': 'Techtronic Industries Company Limited',
    '0688.HK': 'China Overseas Land & Investment Limited',
    '0762.HK': 'China Unicom (Hong Kong) Limited',
    '0823.HK': 'Link Real Estate Investment Trust',
    '0868.HK': 'Xinyi Glass Holdings Limited',
    '0914.HK': 'Anhui Conch Cement Company Limited',
    '0922.HK': 'Anhui Jianghuai Automobile Group Corp., Ltd.',
    '0960.HK': 'Longfor Group Holdings Limited',
    '0968.HK': 'Xinyi Solar Holdings Limited',
    '0992.HK': 'Lenovo Group Limited',
    '1038.HK': 'CK Infrastructure Holdings Limited',
    '1044.HK': 'Hengan International Group Company Limited',
    '1093.HK': 'CSPC Pharmaceutical Group Limited',
    '1109.HK': 'China Resources Land Limited',
    '1113.HK': 'CK Asset Holdings Limited',
    '1177.HK': 'Sino Biopharmaceutical Limited',
    '1199.HK': 'COSCO SHIPPING Ports Limited',
    '1209.HK': 'China Resources Mixc Lifestyle Services Limited',
    '1288.HK': 'Agricultural Bank of China Limited',
    '1378.HK': 'China Hongqiao Group Limited',
    '1928.HK': 'Sands China Ltd.',
    '1929.HK': 'Chow Tai Fook Jewellery Group Limited',
    '2020.HK': 'ANTA Sports Products Limited',
    '2269.HK': 'WuXi Biologics (Cayman) Inc.',
    '2313.HK': 'Shenzhou International Group Holdings Limited',
    '2319.HK': 'China Mengniu Dairy Company Limited',
    '2382.HK': 'Sunny Optical Technology (Group) Company Limited',
    '2388.HK': 'BOC Hong Kong (Holdings) Limited',
    '2600.HK': 'Aluminum Corporation of China Limited',
    '2688.HK': 'ENN Energy Holdings Limited',
    '2899.HK': 'Zijin Mining Group Co., Ltd.',
    '3311.HK': 'China State Construction International Holdings Limited',
    '3323.HK': 'China National Building Material Company Limited',
    '6088.HK': 'FIT Hon Teng Limited',
    '6160.HK': 'Cansino Biologics Inc.',
    '6618.HK': 'JD Health International Inc.',
    '6690.HK': 'Haier Smart Home Co., Ltd.',
    '6862.HK': 'Haidilao International Holding Ltd.',
    '9618.HK': 'JD.com, Inc.',
    '9633.HK': 'Nongfu Spring Co., Ltd.',
    '9888.HK': 'Baidu, Inc.',
    '9999.HK': 'NetEase, Inc.',

    # --- MAINLAND CHINA ON-SHORE (Shanghai: .SS & Shenzhen: .SZ) ---
    '600519.SS': 'Kweichow Moutai Co., Ltd.',
    '601398.SS': 'Industrial and Commercial Bank of China Limited',
    '601857.SS': 'PetroChina Company Limited',
    '601288.SS': 'Agricultural Bank of China Limited',
    '601988.SS': 'Bank of China Limited',
    '600036.SS': 'China Merchants Bank Co., Ltd.',
    '601628.SS': 'China Life Insurance Company Limited',
    '601088.SS': 'China Shenhua Energy Company Limited',
    '600900.SS': 'China Yangtze Power Co., Ltd.',
    '601318.SS': 'Ping An Insurance (Group) Company of China, Ltd.',
    '601166.SS': 'Industrial Bank Co., Ltd.',
    '600030.SS': 'CITIC Securities Company Limited',
    '601328.SS': 'Bank of Communications Co., Ltd.',
    '600016.SS': 'China Minsheng Banking Corp., Ltd.',
    '601939.SS': 'China Construction Bank Corporation',
    '601998.SS': 'China Citic Bank Corporation Limited',
    '601818.SS': 'China Everbright Bank Company Limited',
    '601006.SS': 'Daqin Railway Co., Ltd.',
    '600000.SS': 'Shanghai Pudong Development Bank Co., Ltd.',
    '600019.SS': 'Baoshan Iron & Steel Co., Ltd.',
    '600028.SS': 'China Petroleum & Chemical Corporation',
    '600048.SS': 'Poly Developments and Holdings Group Co., Ltd.',
    '600104.SS': 'SAIC Motor Corporation Limited',
    '600276.SS': 'Jiangsu Hengrui Pharmaceuticals Co., Ltd.',
    '600309.SS': 'Wanhua Chemical Group Co., Ltd.',
    '600406.SS': 'NARI Technology Co., Ltd.',
    '600585.SS': 'Anhui Conch Cement Company Limited',
    '600690.SS': 'Haier Smart Home Co., Ltd.',
    '600809.SS': 'Shanxi Xinghuacun Fen Wine Factory Co., Ltd.',
    '600887.SS': 'Inner Mongolia Yili Industrial Group Co., Ltd.',
    '601111.SS': 'Air China Limited',
    '601138.SS': 'Foxconn Industrial Internet Co., Ltd.',
    '601169.SS': 'Bank of Beijing Co., Ltd.',
    '601211.SS': 'Guotai Junan Securities Co., Ltd.',
    '601229.SS': 'Bank of Shanghai Co., Ltd.',
    '601336.SS': 'New China Life Insurance Company Ltd.',
    '601390.SS': 'China Railway Group Limited',
    '601601.SS': 'China Pacific Insurance (Group) Co., Ltd.',
    '601618.SS': 'Metallurgical Corporation of China Ltd.',
    '601658.SS': 'Postal Savings Bank of China Co., Ltd.',
    '601668.SS': 'China State Construction Engineering Corporation Limited',
    '601688.SS': 'Huatai Securities Co., Ltd.',
    '601728.SS': 'China Telecom Corporation Limited',
    '601766.SS': 'CRRC Corporation Limited',
    '601800.SS': 'China Communications Construction Company Limited',
    '601816.SS': '斬京銀行 (Bank of Nanjing Co., Ltd.)',
    '601888.SS': 'China Tourism Duty Free Corporation Limited',
    '601898.SS': 'China Coal Energy Company Limited',
    '601899.SS': 'Zijin Mining Group Co., Ltd.',
    '601919.SS': 'COSCO SHIPPING Holdings Co., Ltd.',
    '000001.SZ': 'Ping An Bank Co., Ltd.',
    '000002.SZ': 'China Vanke Co., Ltd.',
    '000333.SZ': 'Midea Group Co., Ltd.',
    '000568.SZ': 'Luzhou Laojiao Co., Ltd.',
    '000651.SZ': 'Gree Electric Appliances, Inc. of Zhuhai',
    '000725.SZ': 'BOE Technology Group Co., Ltd.',
    '000768.SZ': 'AVIC Xi\'an Aircraft Industry Group Company Ltd.',
    '000792.SZ': 'Qinghai Salt Lake Industry Co., Ltd.',
    '000858.SZ': 'Wuliangye Yibin Co., Ltd.',
    '002027.SZ': 'Focus Media Information Technology Co., Ltd.',
    '002142.SZ': 'Bank of Ningbo Co., Ltd.',
    '002241.SZ': 'GoerTek Inc.',
    '002304.SZ': 'Jiangsu Yanghe Brewery Joint-Stock Co., Ltd.',
    '002352.SZ': 'S.F. Holding Co., Ltd.',
    '002415.SZ': 'Hangzhou Hikvision Digital Technology Co., Ltd.',
    '002459.SZ': 'EVE Energy Co., Ltd.',
    '002475.SZ': 'Luxshare Precision Industry Co., Ltd.',
    '002594.SZ': 'BYD Company Limited',
    '002714.SZ': 'Muyuan Foods Co., Ltd.',
    '002736.SZ': 'Guosen Securities Co., Ltd.',
    '300015.SZ': 'Aier Eye Hospital Group Co., Ltd.',
    '300059.SZ': 'East Money Information Co., Ltd.',
    '300122.SZ': 'Chongqing Zhifei Biological Products Co., Ltd.',
    '300124.SZ': 'Inovance Technology Co., Ltd.',
    '300274.SZ': 'Sungrow Power Supply Co., Ltd.',
    '300413.SZ': 'Mango Excellent Media Co., Ltd.',
    '300498.SZ': 'Wens Foodstuffs Group Co., Ltd.',
    '300750.SZ': 'Contemporary Amperex Technology Co., Limited (CATL)',
    '300760.SZ': 'Shenzhen Mindray Bio-Medical Electronics Co., Ltd.',
    '002460.SZ': 'Ganfeng Lithium Group Co., Ltd.',

    # --- INDIA (National Stock Exchange: .NS) ---
    'RELIANCE.NS': 'Reliance Industries Limited',
    'TCS.NS': 'Tata Consultancy Services Limited',
    'HDFCBANK.NS': 'HDFC Bank Limited',
    'ICICIBANK.NS': 'ICICI Bank Limited',
    'BHARTIARTL.NS': 'Bharti Airtel Limited',
    'INFY.NS': 'Infosys Limited',
    'SBIN.NS': 'State Bank of India',
    'LIC.NS': 'Life Insurance Corporation of India',
    'ITC.NS': 'ITC Limited',
    'HINDUNILVR.NS': 'Hindustan Unilever Limited',
    'LT.NS': 'Larsen & Toubro Limited',
    'HCLTECH.NS': 'HCL Technologies Limited',
    'BAJFINANCE.NS': 'Bajaj Finance Limited',
    'SUNPHARMA.NS': 'Sun Pharmaceutical Industries Limited',
    'MARUTI.NS': 'Maruti Suzuki India Limited',
    'TATAMOTORS.NS': 'Tata Motors Limited',
    'KOTAKBANK.NS': 'Kotak Mahindra Bank Limited',
    'AXISBANK.NS': 'Axis Bank Limited',
    'NTPC.NS': 'NTPC Limited',
    'ONGC.NS': 'Oil and Natural Gas Corporation Limited',
    'COALINDIA.NS': 'Coal India Limited',
    'ADANIENT.NS': 'Adani Enterprises Limited',
    'ADANIGREEN.NS': 'Adani Green Energy Limited',
    'ADANIPORTS.NS': 'Adani Ports and Special Economic Zone Limited',
    'ADANIPOWER.NS': 'Adani Power Limited',
    'TITAN.NS': 'Titan Company Limited',
    'ULTRACEMCO.NS': 'UltraTech Cement Limited',
    'ASIANPAINT.NS': 'Asian Paints Limited',
    'DMART.NS': 'Avenue Supermarts Limited',
    'BAJAJFINSV.NS': 'Bajaj Finserv Limited',
    'WIPRO.NS': 'Wipro Limited',
    'NESTLEIND.NS': 'Nestle India Limited',
    'JSWSSTEEL.NS': 'JSW Steel Limited',
    'M&M.NS': 'Mahindra & Mahindra Limited',
    'GRASIM.NS': 'Grasim Industries Limited',
    'TATASTEEL.NS': 'Tata Steel Limited',
    'POWERGRID.NS': 'Power Grid Corporation of India Limited',
    'HINDALCO.NS': 'Hindalco Industries Limited',
    'TECHM.NS': 'Tech Mahindra Limited',
    'CIPLA.NS': 'Cipla Limited',
    'DRREDDY.NS': 'Dr. Reddy\'s Laboratories Limited',
    'SBILIFE.NS': 'SBI Life Insurance Company Limited',
    'HDFCLIFE.NS': 'HDFC Life Insurance Company Limited',
    'BPCL.NS': 'Bharat Petroleum Corporation Limited',
    'IOC.NS': 'Indian Oil Corporation Limited',
    'GAIL.NS': 'GAIL (India) Limited',
    'BRITANNIA.NS': 'Britannia Industries Limited',
    'EICHERMOT.NS': 'Eicher Motors Limited',
    'INDUSINDBK.NS': 'IndusInd Bank Limited',
    'DIVISLAB.NS': 'Divi\'s Laboratories Limited',
    'BAJAJ-AUTO.NS': 'Bajaj Auto Limited',
    'APOLLOHOSP.NS': 'Apollo Hospitals Enterprise Limited',
    'VBL.NS': 'Varun Beverages Limited',
    'SHREECEM.NS': 'Shree Cement Limited',
    'TATACONSUM.NS': 'Tata Consumer Products Limited',
    'JIOFIN.NS': 'Jio Financial Services Limited',
    'CHOLAMANDM.NS': 'Cholamandalam Investment and Finance Company Limited',
    'DLF.NS': 'DLF Limited',
    'ZOMATO.NS': 'Zomato Limited',
    'TRENT.NS': 'Trent Limited',
    'RECLTD.NS': 'REC Limited',
    'PFC.NS': 'Power Finance Corporation Limited',
    'GODREJCP.NS': 'Godrej Consumer Products Limited',
    'HEROMOTOCO.NS': 'Hero MotoCorp Limited',
    'LTIM.NS': 'LTIMindtree Limited',
    'BEL.NS': 'Bharat Electronics Limited',
    'HAL.NS': 'Hindustan Aeronautics Limited',
    'SIEMENS.NS': 'Siemens Limited',
    'ABB.NS': 'ABB India Limited',
    'CUMMINSIND.NS': 'Cummins India Limited',
    'PIDILITIND.NS': 'Pidilite Industries Limited',
    'MARICO.NS': 'Marico Limited',
    'BERGEPAINT.NS': 'Berger Paints India Limited',
    'DABUR.NS': 'Dabur India Limited',
    'COLPAL.NS': 'Colgate-Palmolive (India) Limited',
    'UPL.NS': 'UPL Limited',
    'SRF.NS': 'SRF Limited',
    'AMBUJACEM.NS': 'Ambuja Cements Limited',
    'ACC.NS': 'ACC Limited',
    'MUTHOOTFIN.NS': 'Muthoot Finance Limited',
    'PNB.NS': 'Punjab National Bank',
    'BOB.NS': 'Bank of Baroda',
    'CANBK.NS': 'Canara Bank',
    'IDBI.NS': 'IDBI Bank Limited',
    'IOB.NS': 'Indian Overseas Bank',
    'UNIONBANK.NS': 'Union Bank of India',
    'CENTRALBK.NS': 'Central Bank of India',
    'AUROPHARMA.NS': 'Aurobindo Pharma Limited',
    'LUPIN.NS': 'Lupin Limited',
    'BIOCON.NS': 'Biocon Limited',

    # --- TAIWAN (Taiwan Stock Exchange: .TW) ---
    '2330.TW': 'Taiwan Semiconductor Manufacturing Company Limited (TSMC)',
    '2317.TW': 'Hon Hai Precision Industry Co., Ltd. (Foxconn)',
    '2454.TW': 'MediaTek Inc.',
    '2308.TW': 'Delta Electronics, Inc.',
    '2881.TW': 'Fubon Financial Holding Co., Ltd.',
    '2882.TW': 'Cathay Financial Holding Co., Ltd.',
    '2382.TW': 'Quanta Computer Inc.',
    '2412.TW': 'Chunghwa Telecom Co., Ltd.',
    '2303.TW': 'United Microelectronics Corporation (UMC)',
    '2891.TW': 'CTBC Financial Holding Co., Ltd.',
    '1301.TW': 'Formosa Plastics Corporation',
    '1303.TW': 'Nan Ya Plastics Corporation',
    '1326.TW': 'Formosa Chemicals & Fibre Corporation',
    '6505.TW': 'Formosa Petrochemical Corporation',
    '2002.TW': 'China Steel Corporation',
    '2886.TW': 'Mega Financial Holding Co., Ltd.',
    '2885.TW': 'Yuanta Financial Holding Co., Ltd.',
    '3008.TW': 'Largan Precision Co., Ltd.',
    '2379.TW': 'Realtek Semiconductor Corp.',
    '3711.TW': 'ASE Technology Holding Co., Ltd.',
    '2884.TW': 'E.SUN Financial Holding Co., Ltd.',
    '2892.TW': 'First Financial Holding Co., Ltd.',
    '5880.TW': 'Taiwan Cooperative Financial Holding Co., Ltd.',
    '2890.TW': 'Sinopac Financial Holdings Co., Ltd.',
    '2883.TW': 'China Development Financial Holding Corp.',
    '2357.TW': 'ASUSTeK Computer Inc.',
    '4904.TW': 'Far EasTone Telecommunications Co., Ltd.',
    '3045.TW': 'Taiwan Mobile Co., Ltd.',
    '2408.TW': 'Nanya Technology Corporation',
    '2327.TW': 'Yageo Corporation',
    '2603.TW': 'Evergreen Marine Corporation (Taiwan) Ltd.',
    '2609.TW': 'Yang Ming Marine Transport Corporation',
    '2615.TW': 'Wan Hai Lines Ltd.',
    '2301.TW': 'Lite-On Technology Corporation',
    '2395.TW': 'Advantech Co., Ltd.',
    '3231.TW': 'Wistron Corporation',
    '2356.TW': 'Inventec Corporation',
    '2409.TW': 'AUO Corporation',
    '3481.TW': 'Innolux Corporation',
    '1101.TW': 'Taiwan Cement Corporation',
    '1102.TW': 'Asia Cement Corporation',
    '1402.TW': 'Far Eastern New Century Corporation',
    '2105.TW': 'Cheng Shin Rubber Ind. Co., Ltd.',
    '9904.TW': 'Pou Chen Corporation',
    '2912.TW': 'President Chain Store Corporation',
    '5876.TW': 'Shanghai Commercial & Savings Bank, Ltd.',
    '2801.TW': 'Chang Hwa Commercial Bank, Ltd.',
    '2834.TW': 'Taiwan Business Bank',
    '6005.TW': 'Capital Securities Corporation',
    '2887.TW': 'Taishin Financial Holding Co., Ltd.',

    # --- SOUTH KOREA (Korea Exchange: .KS) ---
    '005930.KS': 'Samsung Electronics Co., Ltd.',
    '000660.KS': 'SK Hynix Inc.',
    '373220.KS': 'LG Energy Solution, Ltd.',
    '005380.KS': 'Hyundai Motor Company',
    '000270.KS': 'Kia Corporation',
    '207940.KS': 'Samsung Biologics Co., Ltd.',
    '068270.KS': 'Celltrion, Inc.',
    '035420.KS': 'NAVER Corporation',
    '051910.KS': 'LG Chem, Ltd.',
    '006400.KS': 'Samsung SDI Co., Ltd.',
    '005490.KS': 'POSCO Holdings Inc.',
    '035720.KS': 'Kakao Corp.',
    '105560.KS': 'KB Financial Group Inc.',
    '055550.KS': 'Shinhan Financial Group Co., Ltd.',
    '012330.KS': 'Hyundai Mobis Co., Ltd.',
    '003550.KS': 'LG Corp.',
    '032830.KS': 'Samsung Life Insurance Co., Ltd.',
    '096770.KS': 'SK Innovation Co., Ltd.',
    '015760.KS': 'Korea Electric Power Corporation',
    '000810.KS': 'Samsung Fire & Marine Insurance Co., Ltd.',
    '086790.KS': 'Hana Financial Group Inc.',
    '018260.KS': 'Samsung SDS Co., Ltd.',
    '010140.KS': 'Samsung Heavy Industries Co., Ltd.',
    '033780.KS': 'KT&G Corporation',
    '009150.KS': 'Samsung Electro-Mechanics Co., Ltd.',
    '011170.KS': 'Lotte Chemical Corporation',
    '000720.KS': 'Hyundai Engineering & Construction Co., Ltd.',
    '010950.KS': 'S-Oil Corporation',
    '034220.KS': 'LG Display Co., Ltd.',
    '003670.KS': 'Pohang Coated Steel Co., Ltd. (POSCO C&C)',
    '086280.KS': 'Hyundai Glovis Co., Ltd.',
    '005830.KS': 'DB Insurance Co., Ltd.',
    '011780.KS': 'Kumho Petrochemical Co., Ltd.',
    '034730.KS': 'SK Inc.',
    '017670.KS': 'SK Telecom Co., Ltd.',
    '004020.KS': 'Hyundai Steel Company',
    '097950.KS': 'CJ CheilJedang Corp.',
    '251270.KS': 'Netmarble Corporation',
    '028260.KS': 'Samsung C&T Corporation',
    '323410.KS': 'Kakao Bank Corp.',
    '302440.KS': 'SK Bioscience Co., Ltd.',
    '316140.KS': 'Woori Financial Group Inc.',
    '047050.KS': 'Daewoo Shipbuilding & Marine Engineering Co., Ltd. (Hanwha Ocean)',
    '009830.KS': 'Hanwha Aerospace Co., Ltd.',
    '010130.KS': 'Korea Zinc Co., Ltd.',
    '001040.KS': 'CJ Corporation',
    '024110.KS': 'Industrial Bank of Korea',
    '036570.KS': 'NCSoft Corporation',
    '011200.KS': 'HMM Co., Ltd.',
    '003490.KS': 'Korean Air Lines Co., Ltd.',

    # --- ASEAN (Singapore: .SI, Indonesia: .JK, Malaysia: .KL, Thailand: .BK) ---
    'D05.SI': 'DBS Group Holdings Ltd',
    'O39.SI': 'Oversea-Chinese Banking Corporation Limited',
    'U11.SI': 'United Overseas Bank Limited',
    'Z74.SI': 'Singapore Telecommunications Limited (Singtel)',
    'C52.SI': 'ComfortDelGro Corporation Limited',
    'BS6.SI': 'Yangzijiang Shipbuilding (Holdings) Ltd.',
    'J36.SI': 'Jardine Matheson Holdings Limited',
    'G13.SI': 'Genting Singapore Limited',
    'T39.SI': 'Sembcorp Industries Ltd',
    'BN4.SI': 'Keppel Ltd.',
    'BBCA.JK': 'PT Bank Central Asia Tbk',
    'BBRI.JK': 'PT Bank Rakyat Indonesia (Persero) Tbk',
    'TLKM.JK': 'PT Telkom Indonesia (Persero) Tbk',
    'BMRI.JK': 'PT Bank Mandiri (Persero) Tbk',
    'ASII.JK': 'PT Astra International Tbk',
    'BYAN.JK': 'PT Bayan Resources Tbk',
    'BBNI.JK': 'PT Bank Negara Indonesia (Persero) Tbk',
    'UNVR.JK': 'PT Unilever Indonesia Tbk',
    'AMRT.JK': 'PT Sumber Alfaria Trijaya Tbk',
    'GOTO.JK': 'PT GoTo Gojek Tokopedia Tbk',
    '1155.KL': 'Malayan Banking Berhad (Maybank)',
    '1023.KL': 'CIMB Group Holdings Berhad',
    '5184.KL': 'LPI Capital Bhd',
    '1295.KL': 'Public Bank Berhad',
    '6888.KL': 'Axiata Group Berhad',
    '4011.KL': 'Telekom Malaysia Berhad',
    '5225.KL': 'IHH Healthcare Berhad',
    '1066.KL': 'RHB Bank Berhad',
    '4707.KL': 'Nestle (Malaysia) Berhad',
    '5183.KL': 'Petronas Chemicals Group Berhad',
    'PTT.BK': 'PTT Public Company Limited',
    'DELTA.BK': 'Delta Electronics (Thailand) Public Company Limited',
    'ADVANC.BK': 'Advanced Info Service Public Company Limited',
    'AOT.BK': 'Airports of Thailand Public Company Limited',
    'GULF.BK': 'Gulf Energy Development Public Company Limited',
    'CPALL.BK': 'CP ALL Public Company Limited',
    'BDMS.BK': 'Bangkok Dusit Medical Services Public Company Limited',
    'SCC.BK': 'The Siam Cement Public Company Limited',
    'PTTEP.BK': 'PTT Exploration and Production Public Company Limited',
    'SCB.BK': 'SCB X Public Company Limited'
}

ticker_europe = {
    # France (.PA)
    'MC.PA': 'LVMH Moët Hennessy Louis Vuitton',
    'OR.PA': 'LOréal S.A.',
    'RMS.PA': 'Hermès International',
    'TTE.PA': 'TotalEnergies SE',
    'SAN.PA': 'Sanofi',
    'SU.PA': 'Schneider Electric SE',
    'AI.PA': 'Air Liquide S.A.',
    'AIR.PA': 'Airbus SE',
    'BNP.PA': 'BNP Paribas S.A.',
    'DG.PA': 'Vinci S.A.',
    'CS.PA': 'AXA S.A.',
    'EL.PA': 'EssilorLuxottica',
    'BN.PA': 'Danone S.A.',
    'SAF.PA': 'Safran S.A.',
    'CAP.PA': 'Capgemini SE',
    'ENGI.PA': 'Engie S.A.',
    'SGO.PA': 'Compagnie de Saint-Gobain S.A.',
    'RI.PA': 'Pernod Ricard S.A.',
    'ACA.PA': 'Crédit Agricole S.A.',
    'ORA.PA': 'Orange S.A.',
    'GLE.PA': 'Société Générale S.A.',
    'ML.PA': 'Compagnie Générale des Établissements Michelin',
    'VIE.PA': 'Veolia Environnement S.A.',
    'EN.PA': 'Bouygues S.A.',
    'CA.PA': 'Carrefour S.A.',
    'ALO.PA': 'Alstom S.A.',
    'VIV.PA': 'Vivendi SE',
    'HO.PA': 'Thales S.A.',
    'LR.PA': 'Legrand S.A.',
    'PUB.PA': 'Publicis Groupe S.A.',
    'TEP.PA': 'Teleperformance SE',
    'EDEN.PA': 'Edenred SE',
    'DSY.PA': 'Dassault Systèmes SE',
    'KER.PA': 'Kering S.A.',
    'RNO.PA': 'Renault S.A.',
    'ERF.PA': 'Eurofins Scientific SE',
    'SW.PA': 'Somfy SA',
    'URW.PA': 'Unibail-Rodamco-Westfield SE',
    'AC.PA': 'Accor S.A.',
    'AKE.PA': 'Arkema S.A.',
    'BIM.PA': 'BioMérieux S.A.',
    'BVI.PA': 'Bureau Veritas S.A.',
    'GFC.PA': 'Gecina S.A.',
    'LI.PA': 'Kaufman & Broad S.A.',
    'NEX.PA': 'Nexity S.A.',
    'RCO.PA': 'Rémy Cointreau S.A.',
    'SK.PA': 'Seb S.A.',
    'SOI.PA': 'Soitec S.A.',
    'FRVIA.PA': 'Forvia SE',
    'SCR.PA': 'SCOR SE',

    # Netherlands (.AS)
    'ASML.AS': 'ASML Holding N.V.',
    'INGA.AS': 'ING Groep N.V.',
    'PRX.AS': 'Prosus N.V.',
    'ADYEN.AS': 'Adyen N.V.',
    'WKL.AS': 'Wolters Kluwer N.V.',
    'DSFIR.AS': 'DSM-Firmenich AG',
    'AD.AS': 'Koninklijke Ahold Delhaize N.V.',
    'HEIA.AS': 'Heineken N.V.',
    'PHIA.AS': 'Koninklijke Philips N.V.',
    'AKZA.AS': 'Akzo Nobel N.V.',
    'NN.AS': 'NN Group N.V.',
    'KPN.AS': 'Koninklijke KPN N.V.',
    'ASM.AS': 'ASM International N.V.',
    'RAND.AS': 'Randstad N.V.',
    'AGN.AS': 'Aegon N.V.',
    'LIGHT.AS': 'Signify N.V.',
    'TKWY.AS': 'Just Eat Takeaway.com N.V.',
    'IMCD.AS': 'IMCD N.V.',
    'ABN.AS': 'ABN AMRO Bank N.V.',
    'JDEP.AS': 'JDE Peet\'s N.V.',
    'ARGX.AS': 'argenx SE',
    'OCI.AS': 'OCI N.V.',
    'AALB.AS': 'Aalberts N.V.',
    'FUR.AS': 'Fastned B.V.',
    'VPK.AS': 'Vopak N.V.',
    'SBMO.AS': 'SBM Offshore N.V.',
    'BESI.AS': 'BE Semiconductor Industries N.V.',
    'REN.AS': 'Relx PLC',
    'EXOR.AS': 'Exor N.V.',
    'COR.AS': 'Corbion N.V.',

    # Italy (.MI)
    'ENEL.MI': 'Enel S.p.A.',
    'ENI.MI': 'Eni S.p.A.',
    'ISP.MI': 'Intesa Sanpaolo S.p.A.',
    'UCG.MI': 'UniCredit S.p.A.',
    'RACE.MI': 'Ferrari N.V.',
    'STLAM.MI': 'Stellantis N.V.',
    'G.MI': 'Assicurazioni Generali S.p.A.',
    'SRG.MI': 'Snam S.p.A.',
    'TRN.MI': 'Terna - Rete Elettrica Nazionale S.p.A.',
    'PST.MI': 'Poste Italiane S.p.A.',
    'MONC.MI': 'Moncler S.p.A.',
    'PRY.MI': 'Prysmian S.p.A.',
    'LDO.MI': 'Leonardo S.p.A.',
    'TEN.MI': 'Tenaris S.A.',
    'MB.MI': 'Mediobanca Banca di Credito Finanziario S.p.A.',
    'FBK.MI': 'FinecoBank S.p.A.',
    'BPE.MI': 'BPER Banca S.p.A.',
    'BAMI.MI': 'Banco BPM S.p.A.',
    'NEXI.MI': 'Nexi S.p.A.',
    'TIT.MI': 'Telecom Italia S.p.A.',
    'REC.MI': 'Recordati S.p.A.',
    'AMP.MI': 'Amplifon S.p.A.',
    'DIA.MI': 'DiaSorin S.p.A.',
    'IG.MI': 'Interpump Group S.p.A.',
    'INW.MI': 'Inwit S.p.A.',
    'BC.MI': 'Brunello Cucinelli S.p.A.',
    'SPM.MI': 'Saipem S.p.A.',
    'MT.MI': 'ArcelorMittal S.A.',
    'BRE.MI': 'Brembo S.p.A.',
    'IP.MI': 'ERG S.p.A.',
    'A2A.MI': 'A2A S.p.A.',
    'CPR.MI': 'Capri Holdings Limited',
    'YSY.MI': 'Iveco Group N.V.',
    'PIRC.MI': 'Pirelli & C. S.p.A.',

    # Spain (.MC)
    'IBE.MC': 'Iberdrola S.A.',
    'SAN.MC': 'Banco Santander S.A.',
    'BBVA.MC': 'Banco Bilbao Vizcaya Argentaria S.A.',
    'ITX.MC': 'Industria de Diseño Textil S.A. (Inditex)',
    'AMS.MC': 'Amadeus IT Group S.A.',
    'CABK.MC': 'CaixaBank S.A.',
    'CLNX.MC': 'Cellnex Telecom S.A.',
    'TEF.MC': 'Telefónica S.A.',
    'REP.MC': 'Repsol S.A.',
    'FER.MC': 'Ferrovial SE',
    'AENA.MC': 'Aena S.M.E. S.A.',
    'NTGY.MC': 'Naturgy Energy Group S.A.',
    'RED.MC': 'Redeia Corporación S.A.',
    'ELE.MC': 'Endesa S.A.',
    'GRF.MC': 'Grifols S.A.',
    'ACS.MC': 'ACS, Actividades de Construcción y Servicios S.A.',
    'BKT.MC': 'Bankinter S.A.',
    'ENG.MC': 'Enagás S.A.',
    'MAP.MC': 'Mapfre S.A.',
    'FDR.MC': 'Fluidra S.A.',
    'ANA.MC': 'Acciona S.A.',
    'IDR.MC': 'Indra Sistemas S.A.',
    'SLR.MC': 'Solaria Energía y Medio Ambiente S.A.',
    'COL.MC': 'Inmobiliaria Colonial S.A.R.E.',
    'MRL.MC': 'Merlin Properties SOCIMI S.A.',
    'LOG.MC': 'Logista S.A.',
    'SCYR.MC': 'Sacyr S.A.',
    'UNI.MC': 'Unicaja Banco S.A.',

    # Sweden (.ST)
    'INVE-B.ST': 'Investor AB',
    'ATCO-A.ST': 'Atlas Copco AB',
    'VOLV-B.ST': 'Volvo AB',
    'ERIC-B.ST': 'Telefonaktiebolaget LM Ericsson',
    'HM-B.ST': 'H & M Hennes & Mauritz AB',
    'SEB-A.ST': 'Skandinaviska Enskilda Banken AB',
    'SWED-A.ST': 'Swedbank AB',
    'NDA-SE.ST': 'Nordea Bank Abp',
    'SHB-A.ST': 'Svenska Handelsbanken AB',
    'SAND.ST': 'Sandvik AB',
    'ASSA-B.ST': 'ASSA ABLOY AB',
    'ESSITY-B.ST': 'Essity AB',
    'EVO.ST': 'Evolution AB',
    'HEXA-B.ST': 'Hexagon AB',
    'SKF-B.ST': 'SKF AB',
    'ALFA.ST': 'Alfa Laval AB',
    'BOL.ST': 'Boliden AB',
    'NIBE-B.ST': 'NIBE Industrier AB',
    'TELIA.ST': 'Telia Company AB',
    'EPI-A.ST': 'Epiroc AB',
    'EQT.ST': 'EQT AB',
    'SCA-B.ST': 'Svenska Cellulosa AB SCA',
    'SEC-B.ST': 'Securitas AB',
    'SKA-B.ST': 'Skanska AB',
    'TEL2-B.ST': 'Tele2 AB',
    'GETI-B.ST': 'Getinge AB',
    'CAST.ST': 'Castellum AB',
    'BALD-B.ST': 'Fastighets AB Balder',
    'SAGA-B.ST': 'Sagax AB',
    'EKTA-B.ST': 'Eltel AB',
    'ALIV-SDB.ST': 'Autoliv, Inc.',
    'LUND-B.ST': 'Lundin Mining Corporation',
    'INDT.ST': 'Indutrade AB',
    'LIFCO-B.ST': 'Lifco AB',
    'ADDB.ST': 'Addtech AB',
    'SAAB-B.ST': 'Saab AB',
    'SSAB-A.ST': 'SSAB AB',
    'HOLM-B.ST': 'Holmen AB',

    # Denmark (.CO)
    'NOVO-B.CO': 'Novo Nordisk A/S',
    'DSV.CO': 'DSV A/S',
    'ORSTED.CO': 'Ørsted A/S',
    'VWS.CO': 'Vestas Wind Systems A/S',
    'COLO-B.CO': 'Coloplast A/S',
    'GMAB.CO': 'Genmab A/S',
    'NSIS-B.CO': 'Netcompany Group A/S',
    'MAERSK-B.CO': 'A.P. Møller - Mærsk A/S',
    'CARL-B.CO': 'Carlsberg A/S',
    'DANSKE.CO': 'Danske Bank A/S',
    'JYSK.CO': 'Jyske Bank A/S',
    'DEMANT.CO': 'Demant A/S',
    'GN.CO': 'GN Store Nord A/S',
    'PNDORA.CO': 'Pandora A/S',
    'TRYG.CO': 'Tryg A/S',
    'ISS.CO': 'ISS A/S',
    'RBREW.CO': 'Royal Unibrew A/S',
    'NKT.CO': 'NKT A/S',
    'ROCK-B.CO': 'ROCKWOOL A/S',
    'SYDB.CO': 'Sydbank A/S',

    # Finland (.HE)
    'NDA-FI.HE': 'Nordea Bank Abp',
    'NESTE.HE': 'Neste Oyj',
    'NOKIA.HE': 'Nokia Oyj',
    'SAMPO.HE': 'Sampo Oyj',
    'KNEBV.HE': 'Kone Oyj',
    'UPM.HE': 'UPM-Kymmene Oyj',
    'STEAV.HE': 'Stora Enso Oyj',
    'FORTUM.HE': 'Fortum Oyj',
    'KESKOB.HE': 'Kesko Oyj',
    'ORNBV.HE': 'Orion Oyj',
    'WRT1V.HE': 'Wärtsilä Oyj Abp',
    'METSO.HE': 'Metso Oyj',
    'VALMT.HE': 'Valmet Oyj',
    'ELISA.HE': 'Elisa Oyj',
    'HUH1V.HE': 'Huhtamäki Oyj',
    'KEMIRA.HE': 'Kemira Oyj',
    'CGCIV.HE': 'Cargotec Oyj',
    'TIETO.HE': 'Tietoevry Oyj',
    'QTCOM.HE': 'Qt Group Oyj',
    'METSB.HE': 'Metsä Board Oyj',

    # Belgium (.BR)
    'ABI.BR': 'Anheuser-Busch InBev SA/NV',
    'KBC.BR': 'KBC Group NV',
    'UCB.BR': 'UCB SA',
    'UMI.BR': 'Umicore SA',
    'SOLV.BR': 'Solvay SA',
    'AGS.BR': 'Ageas SA/NV',
    'SYENS.BR': 'Syensqo SA',
    'DIE.BR': 'Dieteren Group',
    'ACKB.BR': 'Ackermans & van Haaren NV',
    'SOF.BR': 'Sofina SA',
    'ELI.BR': 'Elia Group SA',
    'MELE.BR': 'Melexis NV',
    'WDP.BR': 'WDP NV',
    'PROX.BR': 'Proximus NV',
    'LOTB.BR': 'Lotus Bakeries NV',

    # Portugal (.LS)
    'EDP.LS': 'EDP - Energias de Portugal, S.A.',
    'JMT.LS': 'Jerónimo Martins, S.G.P.S., S.A.',
    'GALP.LS': 'Galp Energia, SGPS, S.A.',
    'EDPR.LS': 'EDP Renováveis, S.A.',
    'BCP.LS': 'Banco Comercial Português, S.A.',

    # Austria (.VI)
    'EBS.VI': 'Erste Group Bank AG',
    'OMV.VI': 'OMV AG',
    'VER.VI': 'Verbund AG',
    'RBI.VI': 'Raiffeisen Bank International AG',
    'ANDR.VI': 'Andritz AG',

    # Poland (.WA)
    'PKO.WA': 'Powszechna Kasa Oszczędności Bank Polski S.A.',
    'PKN.WA': 'Polski Koncern Naftowy ORLEN S.A.',
    'PZU.WA': 'Powszechny Zakład Ubezpieczeń S.A.',
    'PEO.WA': 'Bank Pekao S.A.',
    'DNP.WA': 'Dino Polska S.A.'
}

ticker_rotw = {
    # --- UNITED KINGDOM (London Stock Exchange: .L) ---
    'SHEL.L': 'Shell plc', 'AZN.L': 'AstraZeneca plc', 'HSBA.L': 'HSBC Holdings plc',
    'ULVR.L': 'Unilever plc', 'BP.L': 'BP plc', 'GSK.L': 'GSK plc',
    'RIO.L': 'Rio Tinto plc', 'REL.L': 'RELX plc', 'BATS.L': 'British American Tobacco p.l.c.',
    'DGE.L': 'Diageo plc', 'LLOY.L': 'Lloyds Banking Group plc', 'BARC.L': 'Barclays plc',
    'PRU.L': 'Prudential plc', 'EXPN.L': 'Experian plc', 'GLEN.L': 'Glencore plc',
    'NG.L': 'National Grid plc', 'AAL.L': 'Anglo American plc', 'VOD.L': 'Vodafone Group plc',
    'BKT.L': 'Babcock International Group PLC', 'WCPP.L': 'Whitbread PLC',

    # --- SWITZERLAND (SIX Swiss Exchange: .SW) ---
    'NESN.SW': 'Nestlé S.A.', 'ROG.SW': 'Roche Holding AG', 'NOVN.SW': 'Novartis AG',
    'UBSG.SW': 'UBS Group AG', 'CFR.SW': 'Compagnie Financière Richemont S.A.',
    'ZURN.SW': 'Zurich Insurance Group AG', 'ABBN.SW': 'ABB Ltd', 'SIKA.SW': 'Sika AG',
    'LONN.SW': 'Lonza Group AG', 'ALC.SW': 'Alcon Inc.', 'GIVN.SW': 'Givaudan SA',
    'HOLN.SW': 'Holcim Ltd', 'SRENH.SW': 'Swiss Re AG', 'GEBN.SW': 'Geberit AG',
    'SCMN.SW': 'Swisscom AG', 'BAER.SW': 'Julius Bär Gruppe AG', 'LOGN.SW': 'Logitech International S.A.',
    'SOON.SW': 'Sonova Holding AG', 'VATN.SW': 'VAT Group AG', 'SGSN.SW': 'SGS S.A.',

    # --- CANADA (Toronto Stock Exchange: .TO) ---
    'RY.TO': 'Royal Bank of Canada', 'TD.TO': 'The Toronto-Dominion Bank',
    'SHOP.TO': 'Shopify Inc.', 'ENB.TO': 'Enbridge Inc.', 'CNR.TO': 'Canadian National Railway Company',
    'CP.TO': 'Canadian Pacific Kansas City Limited', 'CNQ.TO': 'Canadian Natural Resources Limited',
    'BMO.TO': 'Bank of Montreal', 'ATD.TO': 'Alimentation Couche-Tard Inc.',
    'TRI.TO': 'Thomson Reuters Corporation', 'BAM.TO': 'Brookfield Asset Management Ltd.',
    'SU.TO': 'Suncor Energy Inc.', 'MFC.TO': 'Manulife Financial Corporation',
    'BNS.TO': 'Bank of Nova Scotia', 'ABX.TO': 'Barrick Gold Corporation',
    'WPM.TO': 'Wheaton Precious Metals Corp.', 'IMO.TO': 'Imperial Oil Limited',
    'SLF.TO': 'Sun Life Financial Inc.', 'CVE.TO': 'Cenovus Energy Inc.',
    'TRP.TO': 'TC Energy Corporation', 'FNV.TO': 'Franco-Nevada Corporation',
    'AEM.TO': 'Agnico Eagle Mines Limited', 'GIB-A.TO': 'CGI Inc.',
    'TEL.TO': 'TELUS Corporation', 'BCE.TO': 'BCE Inc.', 'RCI-B.TO': 'Rogers Communications Inc.',
    'QLSR.TO': 'Dollarama Inc.', 'WCN.TO': 'Waste Connections, Inc.', 'H.TO': 'Hydro One Limited',
    'POW.TO': 'Power Corporation of Canada',

    # --- AUSTRALIA (Australian Securities Exchange: .AX) ---
    'BHP.AX': 'BHP Group Limited', 'CBA.AX': 'Commonwealth Bank of Australia',
    'CSL.AX': 'CSL Limited', 'NAB.AX': 'National Australia Bank Limited',
    'WBC.AX': 'Westpac Banking Corporation', 'ANZ.AX': 'ANZ Group Holdings Limited',
    'MQG.AX': 'Macquarie Group Limited', 'WDS.AX': 'Woodside Energy Group Ltd',
    'WES.AX': 'Wesfarmers Limited', 'WOW.AX': 'Woolworths Group Limited',
    'FMG.AX': 'Fortescue Ltd', 'RIO.AX': 'Rio Tinto Limited', 'GMG.AX': 'Goodman Group',
    'TLS.AX': 'Telstra Group Limited', 'APA.AX': 'APA Group', 'ALL.AX': 'Aristocrat Leisure Limited',
    'QAN.AX': 'Qantas Airways Limited', 'SUN.AX': 'Suncorp Group Limited',
    'IAG.AX': 'Insurance Australia Group Limited', 'XRO.AX': 'Xero Limited',

    # --- LATIN AMERICA (Brazil: .SA & Mexico: .MX) ---
    'VALE3.SA': 'Vale S.A.', 'PETR4.SA': 'Petróleo Brasileiro S.A.',
    'ITUB4.SA': 'Itaú Unibanco Holding S.A.', 'BBDC4.SA': 'Banco Bradesco S.A.',
    'BBAS3.SA': 'Banco do Brasil S.A.', 'ABEV3.SA': 'Ambev S.A.',
    'WEGE3.SA': 'WEG S.A.', 'ITSA4.SA': 'Itaúsa S.A.', 'B3SA3.SA': 'B3 S.A.',
    'RENT3.SA': 'Localiza Rent a Car S.A.', 'AMXL.MX': 'América Móvil, S.A.B. de C.V.',
    'WALMEX.MX': 'Wal-Mart de México, S.A.B. de C.V.',
    'FEMSAUBD.MX': 'Fomento Económico Mexicano, S.A.B. de C.V.',
    'GMEXICOB.MX': 'Grupo México, S.A.B. de C.V.',
    'GFNORTEO.MX': 'Grupo Financiero Banorte, S.A.B. de C.V.',
    'CEMEXCPO.MX': 'Cemex, S.A.B. de C.V.', 'BIMBOA.MX': 'Grupo Bimbo, S.A.B. de C.V.',
    'ALPEKA.MX': 'Alfa, S.A.B. de C.V.', 'GRUMAB.MX': 'Gruma, S.A.B. de C.V.',
    'ORBIA.MX': 'Orbia Advance Corporation, S.A.B. de C.V.'
}