import yfinance as yf
import pandas as pd
import requests
from datetime import datetime, timedelta
import os

ticker_us = {
    'AAPL': 'Apple Inc.', 'MSFT': 'Microsoft Corporation', 'NVDA': 'NVIDIA Corporation', 
    'AMZN': 'Amazon.com, Inc.', 'GOOGL': 'Alphabet Inc. Class A', 'GOOG': 'Alphabet Inc. Class C', 
    'META': 'Meta Platforms, Inc.', 'BRK.B': 'Berkshire Hathaway Inc. Class B', 'LLY': 'Eli Lilly and Company', 
    'AVGO': 'Broadcom Inc.', 'TSLA': 'Tesla, Inc.', 'JPM': 'JPMorgan Chase & Co.', 
    'UNH': 'UnitedHealth Group Incorporated', 'V': 'Visa Inc.', 'XOM': 'Exxon Mobil Corporation', 
    'MA': 'Mastercard Incorporated', 'HD': 'The Home Depot, Inc.', 'PG': 'The Procter & Gamble Company', 
    'COST': 'Costco Wholesale Corporation', 'JNJ': 'Johnson & Johnson', 'AMD': 'Advanced Micro Devices, Inc.', 
    'NFLX': 'Netflix, Inc.', 'ABBV': 'AbbVie Inc.', 'ORCL': 'Oracle Corporation', 
    'CRM': 'Salesforce, Inc.', 'BAC': 'Bank of America Corporation', 'CVX': 'Chevron Corporation', 
    'WMT': 'Walmart Inc.', 'MRK': 'Merck & Co., Inc.', 'WFC': 'Wells Fargo & Company', 
    'DIS': 'The Walt Disney Company', 'PEP': 'PepsiCo, Inc.', 'CSCO': 'Cisco Systems, Inc.', 
    'ADBE': 'Adobe Inc.', 'KO': 'The Coca-Cola Company', 'TMO': 'Thermo Fisher Scientific Inc.', 
    'QCOM': 'QUALCOMM Incorporated', 'ACN': 'Accenture plc', 'GE': 'General Electric Company', 
    'LIN': 'Linde plc', 'MCD': 'McDonald\'s Corporation', 'PM': 'Philip Morris International Inc.', 
    'ABT': 'Abbott Laboratories', 'AXP': 'American Express Company', 'ISRG': 'Intuitive Surgical, Inc.', 
    'IBM': 'International Business Machines Corporation', 'TXN': 'Texas Instruments Incorporated', 
    'MS': 'Morgan Stanley', 'GS': 'The Goldman Sachs Group, Inc.', 'AMGN': 'Amgen Inc.', 
    'HON': 'Honeywell International Inc.', 'CAT': 'Caterpillar Inc.', 'SPGI': 'S&P Global Inc.', 
    'BKNG': 'Booking Holdings Inc.', 'NOW': 'ServiceNow, Inc.', 'PFE': 'Pfizer Inc.', 
    'NKE': 'NIKE, Inc.', 'INTU': 'Intuit Inc.', 'LOW': 'Lowe\'s Companies, Inc.', 
    'COP': 'ConocoPhillips', 'SYK': 'Stryker Corporation', 'C': 'Citigroup Inc.', 
    'LRCX': 'Lam Research Corporation', 'BLK': 'BlackRock, Inc.', 'TJX': 'The TJX Companies, Inc.', 
    'UNP': 'Union Pacific Corporation', 'REGN': 'Regeneron Pharmaceuticals, Inc.', 
    'PLTR': 'Palantir Technologies Inc.', 'MDLZ': 'Mondelez International, Inc.', 
    'BA': 'The Boeing Company', 'VRTX': 'Vertex Pharmaceuticals Incorporated', 
    'ADI': 'Analog Devices, Inc.', 'AXON': 'Axon Enterprise, Inc.', 'UBER': 'Uber Technologies, Inc.', 
    'BX': 'Blackstone Inc.', 'PANW': 'Palo Alto Networks, Inc.', 'DE': 'Deere & Company', 
    'CI': 'The Cigna Group', 'ELV': 'Elevance Health, Inc.', 'CB': 'Chubb Limited', 
    'GILD': 'Gilead Sciences, Inc.', 'MMC': 'Marsh & McLennan Companies, Inc.', 
    'LMT': 'Lockheed Martin Corporation', 'AMAT': 'Applied Materials, Inc.', 
    'MU': 'Micron Technology, Inc.', 'KKR': 'KKR & Co. Inc.', 'MDT': 'Medtronic plc', 
    'ANET': 'Arista Networks, Inc.', 'CRWD': 'CrowdStrike Holdings, Inc.', 
    'KLAC': 'KLA Corporation', 'HCA': 'HCA Healthcare, Inc.', 'FI': 'Fiserv, Inc.', 
    'CDNS': 'Cadence Design Systems, Inc.', 'GEV': 'GE Vernova Inc.', 'ICE': 'Intercontinental Exchange, Inc.', 
    'ETN': 'Eaton Corporation plc', 'MO': 'Altria Group, Inc.', 'WM': 'Waste Management, Inc.', 
    'SHW': 'The Sherwin-Williams Company', 'EOG': 'EOG Resources, Inc.', 'ORLY': 'O\'Reilly Automotive, Inc.', 
    'T': 'AT&T Inc.', 'BSX': 'Boston Scientific Corporation', 'PGR': 'The Progressive Corporation', 
    'CMG': 'Chipotle Mexican Grill, Inc.', 'DUK': 'Duke Energy Corporation', 'PH': 'Parker-Hannifin Corporation', 
    'NOC': 'Northrop Grumman Corporation', 'GD': 'General Dynamics Corporation', 
    'MCK': 'McKesson Corporation', 'MAR': 'Marriott International, Inc.', 
    'SLB': 'SLB (Schlumberger)', 'CTAS': 'Cintas Corporation', 'NXPI': 'NXP Semiconductors N.V.', 
    'CVS': 'CVS Health Corporation', 'MPC': 'Marathon Petroleum Corporation', 
    'TT': 'Trane Technologies plc', 'SNPS': 'Synopsys, Inc.', 'APH': 'Amphenol Corporation', 
    'ECL': 'Ecolab Inc.', 'ITW': 'Illinois Tool Works Inc.', 'EMR': 'Emerson Electric Co.', 
    'COR': 'Cencora, Inc.', 'HUM': 'Humana Inc.', 'ADSK': 'Autodesk, Inc.', 
    'AON': 'Aon plc', 'MCO': 'Moody\'s Corporation', 'ROST': 'Ross Stores, Inc.', 
    'PCAR': 'PACCAR Inc.', 'HLT': 'Hilton Worldwide Holdings Inc.', 'AIG': 'American International Group, Inc.', 
    'BKR': 'Baker Hughes Company', 'AEP': 'American Electric Power Company, Inc.', 
    'WELL': 'Welltower Inc.', 'PAYX': 'Paychex, Inc.', 'DHR': 'Danaher Corporation', 
    'CARR': 'Carrier Global Corporation', 'FIS': 'Fidelity National Information Services, Inc.', 
    'TEL': 'TE Connectivity Ltd.', 'O': 'Realty Income Corporation', 'D': 'Dominion Energy, Inc.', 
    'KMB': 'Kimberly-Clark Corporation', 'MNST': 'Monster Beverage Corporation', 
    'TRV': 'The Travelers Companies, Inc.', 'OKE': 'ONEOK, Inc.', 'CMI': 'Cummins Inc.', 
    'AZO': 'AutoZone, Inc.', 'FDX': 'FedEx Corporation', 'SPG': 'Simon Property Group, Inc.', 
    'CPRT': 'Copart, Inc.', 'AJG': 'Arthur J. Gallagher & Co.', 'SBUX': 'Starbucks Corporation', 
    'MET': 'MetLife, Inc.', 'GIS': 'General Mills, Inc.', 'HAL': 'Halliburton Company', 
    'LEN': 'Lennar Corporation', 'ALL': 'The Allstate Corporation', 'OXY': 'Occidental Petroleum Corporation', 
    'GWW': 'W.W. Grainger, Inc.', 'NSC': 'Norfolk Southern Corporation', 'PSA': 'Public Storage', 
    'DLR': 'Digital Realty Trust, Inc.', 'KDP': 'Keurig Dr Pepper Inc.', 'VRSK': 'Verisk Analytics, Inc.', 
    'ED': 'Consolidated Edison, Inc.', 'ODFL': 'Old Dominion Freight Line, Inc.', 
    'HWM': 'Howmet Aerospace Inc.', 'FAST': 'Fastenal Company', 'PRU': 'Prudential Financial, Inc.', 
    'CTVA': 'Corteva, Inc.', 'YUM': 'Yum! Brands, Inc.', 'EXC': 'Exelon Corporation', 
    'STZ': 'Constellation Brands, Inc.', 'AFL': 'Aflac Incorporated', 'WMB': 'The Williams Companies, Inc.', 
    'VICI': 'VICI Properties Inc.', 'XEL': 'Xcel Energy Inc.', 'KR': 'The Kroger Co.', 
    'IDXX': 'IDEXX Laboratories, Inc.', 'CEG': 'Constellation Energy Corporation', 
    'URI': 'United Rentals, Inc.', 'ROK': 'Rockwell Automation, Inc.', 'CSX': 'CSX Corporation', 
    'HPQ': 'HP Inc.', 'EA': 'Electronic Arts Inc.', 'LUV': 'Southwest Airlines Co.', 
    'CNC': 'Centene Corporation', 'MTD': 'Mettler-Toledo International Inc.', 
    'EFX': 'Equifax Inc.', 'KMI': 'Kinder Morgan, Inc.', 'DAL': 'Delta Air Lines, Inc.', 
    'PEG': 'Public Service Enterprise Group Incorporated', 'RMD': 'ResMed Inc.', 
    'VLO': 'Valero Energy Corporation', 'CTSH': 'Cognizant Technology Solutions Corporation', 
    'WTW': 'Willis Towers Watson Public Limited Company', 'KEYS': 'Keysight Technologies, Inc.', 
    'FITB': 'Fifth Third Bancorp', 'STT': 'State Street Corporation', 'FTV': 'Fortive Corporation', 
    'PPG': 'PPG Industries, Inc.', 'SYY': 'Sysco Corporation', 'EQIX': 'Equinix, Inc.', 
    'EIX': 'Edison International', 'CDW': 'CDW Corporation', 'CBRE': 'CBRE Group, Inc.', 
    'TFC': 'Truist Financial Corporation', 'GLW': 'Corning Incorporated', 'ADM': 'Archer-Daniels-Midland Company', 
    'WST': 'West Pharmaceutical Services, Inc.', 'CAH': 'Cardinal Health, Inc.', 
    'DLTR': 'Dollar Tree, Inc.', 'FMC': 'FMC Corporation', 'VMC': 'Vulcan Materials Company', 
    'BBY': 'Best Buy Co., Inc.', 'BALL': 'Ball Corporation', 'NVR': 'NVR, Inc.', 
    'HUBB': 'Hubbell Incorporated', 'DOV': 'Dover Corporation', 'HIG': 'The Hartford Financial Services Group, Inc.', 
    'BRO': 'Brown & Brown, Inc.', 'IRM': 'Iron Mountain Incorporated', 'STX': 'Seagate Technology Holdings plc', 
    'NDAQ': 'Nasdaq, Inc.', 'SRE': 'Sempra', 'WEC': 'WEC Energy Group, Inc.', 
    'SBAC': 'SBA Communications Corporation', 'NTRS': 'Northern Trust Corporation', 
    'ALGN': 'Align Technology, Inc.', 'TYL': 'Tyler Technologies, Inc.', 'AWK': 'American Water Works Company, Inc.', 
    'WDC': 'Western Digital Corporation', 'GDDY': 'GoDaddy Inc.', 'WBD': 'Warner Bros. Discovery, Inc.', 
    'NTAP': 'NetApp, Inc.', 'BXP': 'BXP, Inc.', 'HES': 'Hess Corporation', 'CL': 'Colgate-Palmolive Company', 
    'ALB': 'Albemarle Corporation', 'A': 'Agilent Technologies, Inc.', 'DPZ': 'Domino\'s Pizza, Inc.', 
    'TROW': 'T. Rowe Price Group, Inc.', 'IEX': 'IDEX Corporation', 'ES': 'Eversource Energy', 
    'FE': 'FirstEnergy Corp.', 'DRI': 'Darden Restaurants, Inc.', 'SWKS': 'Skyworks Solutions, Inc.', 
    'DTE': 'DTE Energy Company', 'JBHT': 'J.B. Hunt Transport Services, Inc.', 
    'TSCO': 'Tractor Supply Company', 'ARE': 'Alexandria Real Estate Equities, Inc.', 
    'BG': 'Bunge Global SA', 'AOS': 'A. O. Smith Corporation', 'INVH': 'Invitation Homes Inc.', 
    'WY': 'Weyerhaeuser Company', 'AVY': 'Avery Dennison Corporation', 'APA': 'APA Corporation', 
    'RF': 'Regions Financial Corporation', 'HBAN': 'Huntington Bancshares Incorporated', 
    'EXR': 'Extra Space Storage Inc.', 'COO': 'The Cooper Companies, Inc.', 
    'EQR': 'Equity Residential', 'VTR': 'Ventas, Inc.', 'AKAM': 'Akamai Technologies, Inc.', 
    'IFF': 'International Flavors & Fragrances Inc.', 'MGM': 'MGM Resorts International', 
    'ZBRA': 'Zebra Technologies Corporation', 'HAS': 'Hasbro, Inc.', 'SNA': 'Snap-on Incorporated', 
    'OMC': 'Omnicom Group Inc.', 'K': 'Kellanova', 'RE': 'Everest Group, Ltd.', 
    'SWK': 'Stanley Black & Decker, Inc.', 'XYL': 'Xylem Inc.', 'CHRW': 'C.H. Robinson Worldwide, Inc.', 
    'IP': 'International Paper Company', 'LKQ': 'LKQ Corporation', 'TAP': 'Molson Coors Beverage Company', 
    'LNT': 'Alliant Energy Corporation', 'AIZ': 'Assurant, Inc.', 'CPB': 'Campbell Soup Company', 
    'JNPR': 'Juniper Networks, Inc.', 'TPR': 'Tapestry, Inc.', 'ALLE': 'Allegion plc', 
    'ZION': 'Zions Bancorporation, N.A.', 'PNR': 'Pentair plc', 'XRAY': 'Dentsply Sirona Inc.', 
    'NWL': 'Newell Brands Inc.', 'FRT': 'Federal Realty Investment Trust', 
    'CMA': 'Comerica Incorporated', 'HRL': 'Hormel Foods Corporation', 'MHK': 'Mohawk Industries, Inc.', 
    'AAL': 'American Airlines Group Inc.', 'SEE': 'Sealed Air Corporation', 
    'NWSA': 'News Corporation Class A', 'NWS': 'News Corporation Class B', 
    'FOXA': 'Fox Corporation Class A', 'FOX': 'Fox Corporation Class B', 
    'DELL': 'Dell Technologies Inc.', 'VST': 'Vistra Corp.', 'CE': 'Celanese Corporation', 
    'MCHP': 'Microchip Technology Incorporated', 'TER': 'Teradyne, Inc.', 
    'QRVO': 'Qorvo, Inc.', 'MPWR': 'Monolithic Power Systems, Inc.', 'FSLR': 'First Solar, Inc.', 
    'ENPH': 'Enphase Energy, Inc.', 'ON': 'ON Semiconductor Corporation', 
    'KVUE': 'Kenvue Inc.', 'GEHC': 'GE HealthCare Technologies Inc.', 
    'SMCI': 'Super Micro Computer, Inc.', 'HPE': 'Hewlett Packard Enterprise Company', 
    'PSTG': 'Pure Storage, Inc.', 'SOFI': 'SoFi Technologies, Inc.', 'APO': 'Apollo Global Management, Inc.', 
    'BEN': 'Franklin Resources, Inc.', 'IVZ': 'Invesco Ltd.', 'AMP': 'Ameriprise Financial, Inc.', 
    'COF': 'Capital One Financial Corporation', 'DFS': 'Discover Financial Services', 
    'AMCR': 'Amcor plc', 'AEE': 'Ameren Corporation', 'ATO': 'Atmos Energy Corporation', 
    'AVB': 'AvalonBay Communities, Inc.', 'BAX': 'Baxter International Inc.', 
    'BDX': 'Becton, Dickinson and Company', 'BF.B': 'Brown-Forman Corporation Class B', 
    'BIIB': 'Biogen Inc.', 'BIO': 'Bio-Rad Laboratories, Inc.', 'BK': 'The Bank of New York Mellon Corporation', 
    'BMY': 'Bristol-Myers Squibb Company', 'BR': 'Broadridge Financial Solutions, Inc.', 
    'CAG': 'Conagra Brands, Inc.', 'CCI': 'Crown Castle Inc.', 'CCL': 'Carnival Corporation & plc', 
    'CF': 'CF Industries Holdings, Inc.', 'CFG': 'Citizens Financial Group, Inc.', 
    'CHD': 'Church & Dwight Co., Inc.', 'CINF': 'Cincinnati Financial Corporation', 
    'CLX': 'The Clorox Company', 'CME': 'CME Group Inc.', 'CMS': 'CMS Energy Corporation', 
    'CNP': 'CenterPoint Energy, Inc.', 'CPT': 'Camden Property Trust', 'CRL': 'Charles River Laboratories International, Inc.', 
    'CSGP': 'CoStar Group, Inc.', 'CTRA': 'Coterra Energy Inc.', 'CZR': 'Caesars Entertainment, Inc.', 
    'DAY': 'RPM International Inc.', 'DD': 'DuPont de Nemours, Inc.', 'DG': 'Dollar General Corporation', 
    'DGX': 'Quest Diagnostics Incorporated', 'DHI': 'D.R. Horton, Inc.', 'DISH': 'DISH Network Corporation', 
    'DOW': 'Dow Inc.', 'DVA': 'DaVita Inc.', 'DVN': 'Devon Energy Corporation', 
    'DXCM': 'DexCom, Inc.', 'DXC': 'DXC Technology Company', 'EG': 'Everest Group, Ltd.', 
    'EL': 'The Estée Lauder Companies Inc.', 'EMN': 'Eastman Chemical Company', 
    'ESS': 'Essex Property Trust, Inc.', 'ETR': 'Entergy Corporation', 'ETY': 'Eaton Vance Tax-Managed Buy-Write Opportunities Fund', 
    'EVRG': 'Evergy, Inc.', 'EW': 'Edwards Lifesciences Corporation', 'EXPD': 'Expeditors International of Washington, Inc.', 
    'EXPE': 'Expedia Group, Inc.', 'FANG': 'Diamondback Energy, Inc.', 'FICO': 'Fair Isaac Corporation', 
    'GEN': 'Gen Digital Inc.', 'GL': 'Globe Life Inc.', 'GNRC': 'Generac Holdings Inc.', 
    'GPC': 'Genuine Parts Company', 'GPN': 'Global Payments Inc.', 'GRMN': 'Garmin Ltd.', 
    'HII': 'Huntington Ingalls Industries, Inc.', 'HOLX': 'Hologic, Inc.', 
    'HSIC': 'Henry Schein, Inc.', 'HST': 'Host Hotels & Resorts, Inc.', 'HSY': 'The Hershey Company', 
    'ILMN': 'Illumina, Inc.', 'INCY': 'Incyte Corporation', 'IPG': 'The Interpublic Group of Companies, Inc.', 
    'IQV': 'IQVIA Holdings Inc.', 'IR': 'Ingersoll Rand Inc.', 'IT': 'Gartner, Inc.', 
    'J': 'Jacobs Solutions Inc.', 'JBL': 'Jabil Inc.', 'JCI': 'Johnson Controls International plc', 
    'JKHY': 'Jack Henry & Associates, Inc.', 'KIM': 'Kimco Realty Corporation', 
    'KMX': 'CarMax, Inc.', 'L': 'Loews Corporation', 'LDOS': 'Leidos Holdings, Inc.', 
    'LH': 'Laboratory Corporation of America Holdings', 'LHX': 'L3Harris Technologies, Inc.', 
    'LII': 'Lennox International Inc.', 'LULU': 'Lululemon Athletica Inc.', 
    'MKC': 'McCormick & Company, Incorporated', 'MKTX': 'MarketAxess Holdings Inc.', 
    'MLM': 'Martin Marietta Materials, Inc.', 'MRNA': 'Moderna, Inc.', 'MSI': 'Motorola Solutions, Inc.', 
    'MTB': 'M&T Bank Corporation', 'NEM': 'Newmont Corporation', 'NRG': 'NRG Energy, Inc.', 
    'NUE': 'Nucor Corporation', 'PARA': 'Paramount Global', 'PAYC': 'Paycom Software, Inc.', 
    'PCTY': 'Paylocity Holding Corporation', 'PENN': 'PENN Entertainment, Inc.', 
    'PFG': 'Principal Financial Group, Inc.', 'PNW': 'Pinnacle West Capital Corporation', 
    'POOL': 'Pool Corporation', 'PTC': 'PTC Inc.', 'PWR': 'Quanta Services, Inc.', 
    'RHI': 'Robert Half Inc.', 'RL': 'Ralph Lauren Corporation', 'RNG': 'RingCentral, Inc.', 
    'SJM': 'The J. M. Smucker Company', 'SNOW': 'Snowflake Inc.', 'SOLV': 'Solventum Corporation', 
    'SQ': 'Block, Inc.', 'SRCL': 'Stericycle, Inc.', 'SSNC': 'SS&C Technologies Holdings, Inc.', 
    'SUM': 'Summit Materials, Inc.', 'SYF': 'Synchrony Financial', 'TECH': 'Bio-Techne Corporation', 
    'TENB': 'Tenable Holdings, Inc.', 'TEX': 'Terex Corporation', 'TFX': 'Teleflex Incorporated', 
    'TGNA': 'TEGNA Inc.', 'TGT': 'Target Corporation', 'THC': 'Tenet Healthcare Corporation', 
    'TKR': 'Timken Company', 'TMUS': 'T-Mobile US, Inc.', 'TPX': 'Tempur Sealy International, Inc.', 
    'TRMB': 'Trimble Inc.', 'TTC': 'The Toro Company', 'TXG': '10x Genomics, Inc.', 
    'UA': 'Under Armour, Inc. Class C', 'UAA': 'Under Armour, Inc. Class A', 
    'UAL': 'United Airlines Holdings, Inc.', 'UDR': 'UDR, Inc.', 'UHS': 'Universal Health Services, Inc.', 
    'ULTA': 'Ulta Beauty, Inc.', 'VFC': 'V.F. Corporation', 'VNO': 'Vornado Realty Trust', 
    'VNT': 'Vontier Corporation', 'VRSN': 'VeriSign, Inc.', 'VTRS': 'Viatris Inc.', 
    'WAB': 'Westinghouse Air Brake Technologies Corporation', 'WAT': 'Waters Corporation', 
    'WBA': 'Walgreens Boots Alliance, Inc.', 'WHR': 'Whirlpool Corporation'
}